SU-SWS/stanford_profile

.gitignore
composer.json
config/install/core.extension.yml
stanford_profile.info.yml
tests/behat/features/contrib/config_readonly.feature

- Enables config_readonly
- End of sprint
- Low
1. See https://github.com/SU-SWS/acsf-cardinalsites/pull/14
- cardinalsites stack
- D8CORE-153
- https://github.com/SU-SWS/acsf-cardinalsites/pull/14

D8CORE-153: Enable config_readonly

---

composer.json
config/sync/core.extension.yml
config/sync/file_mdm_font.file_metadata_plugin.font.yml
config/sync/image.style.stanford_circle.yml
config/sync/image_effects.settings.yml
config/sync/stanford_media.settings.yml

see https://github.com/SU-SWS/stanford_image_styles/pull/47
- Add image_effects module
- added an image style that produces a 140px side circle image.
- 9/25
- low
1. `composer require su-sws/stanford_image_styles:dev-D8CORE-492-circle-image-style`
1. create a basic page, add an image to the wysiwyg and choose the "Circle" image style
1. verify the resulting image is a circle.

D8CORE-492 Circle Image Style

---

composer.json
config/sync/config_pages.type.stanford_basic_site_settings.yml
config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
config/sync/core.entity_view_mode.config_pages.full.yml
config/sync/core.extension.yml
config/sync/domain_301_redirect.settings.yml
config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_url.yml
config/sync/field.storage.config_pages.su_site_url.yml
config/sync/user.role.site_manager.yml
modules/stanford_profile_config_overrides/src/Config/ConfigOverrides.php
modules/stanford_profile_config_overrides/stanford_profile_config_overrides.info.yml
modules/stanford_profile_config_overrides/stanford_profile_config_overrides.services.yml
modules/stanford_profile_config_overrides/tests/src/Unit/Config/ConfigOverridesTest.php

- Use config_pages module to create a page for users to set values for the site
- set up domain 301 redirect to redirect all traffic to a canonical url.
- 9/25
- medium
1. `composer require su-sws/stanford_profile:dev-D8CORE-322-domain-redirect`
1. navigate to `/admin/config/system/basic-site-settings`
1. enter a url. anything URL that is different from your current will work & save
1. view the site as anonymous
1. validate it redirects you off to the domain you configured

D8CORE-322 Use domain redirect and config pages to allow custom domains

---

composer.json
config/sync/core.extension.yml
config/sync/views.settings.yml
config/sync/views.view.content.yml

- Added missing views.settings.yml that fixes https://www.drupal.org/project/drupal/issues/2955877
- added missing admin/content view
- modified admin/content view to use VBO
- 9/26
- Medium
1. in cardinalsites stack `composer require su-sws/stanford_profile:dev-D8CORE-493-vbo`
1. `drush cim -y` or `blt drupal:install`
1. view `/admin/content` path
1. validate you can bulk select content and publish/unpublish/delete/change author

D8CORE-493 Views bulk operations on content list.

---

composer.json
config/sync/config_split.config_split.dev.yml
config/sync/config_split.config_split.prod.yml
config/sync/config_split.config_split.stage.yml
config/sync/core.extension.yml
config/sync/quicklink.settings.yml

See https://github.com/SU-SWS/acsf-cardinalsites/pull/23
- Use sessionless bigpipe - not 100% sure how much improvement this does but it doesnt hurt.
- Use quicklink module. 
- This fetches other links into the browser for anonymous user during network idle time.
- This does 2 things: prime varnish caches for those pages & prefetches for faster load times for the user
- The traffic only occurs during idle time and each link appears to be only about 5KB of data (less than the favicon which is 34KB)
- Quicklink doesnt appear to operate when on "slow 3g" speeds
- Fixed cache invalidation by enabling the required modules.
- asap
- medium
1. review https://d8core329-dev.sites.stanford.edu/
1. edit/create a page
1. view that page logged out and ensure your changes are there
1. edit the page …

D8CORE-329 Use bigpipe and quicklink

---

composer.json
config/sync/config_pages.type.stanford_basic_site_settings.yml
config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
config/sync/core.extension.yml
config/sync/field.field.config_pages.stanford_basic_site_settings.su_google_analytics.yml
config/sync/field.storage.config_pages.su_google_analytics.yml
config/sync/field_validation.rule_set.config_pages_stanford_basic_site_settings.yml
config/sync/google_analytics.settings.yml
tests/behat/features/SystemSiteConfig.feature

- Added google analytics config pages and override.
- 11/6
- low
1. config import
1. cache clear
1. go to `/admin/config/system/basic-site-settings` and enter some garbage text into the google analytics field
1. validate an error appears when you save
1. enter a valid format GA code
1. on the homepage as anonymous view the source and validate the GA code has been added at the top.

D8CORE-386 Added google analytics config override

---

CHANGELOG.md
modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
modules/stanford_profile_config_overrides/stanford_profile_config_overrides.info.yml
modules/stanford_profile_install/stanford_profile_install.info.yml
modules/stanford_profile_styles/stanford_profile_styles.info.yml
stanford_profile.info.yml

Release notes:
```
- Alpha 2 Release
- Require new modules: field_validation, layout_builder_restrictions
- Updated version requirement for pathauto
- New basic site settings for google google_analytics
- Changed default layouts for stanford_page to new jumpstart_ui dynamic layouts
- Enabled modules: field_validation, google_analytics, layout_builder_restrictions, path_alias
- Updated primary and secondary navigation settings.
- New features and functionality.
- New versions
- Deploy and run both database updates and config import
- New version requirements
- Sensitivity around path and path_alias modules
- https://github.com/SU-SWS/stanford_profile/compare/8.1.0-alpha.1...8.1.0-alpha.2
```

8.1.0-alpha.2

---

config/sync/user.role.site_builder.yml
config/sync/user.role.site_developer.yml
config/sync/user.role.site_manager.yml
src/StanfordProfilePermissions.php
stanford_profile.permissions.yml
stanford_profile.profile
tests/behat/features/Users/Roles.feature
tests/src/Kernel/StanfordProfilePermissionsTest.php

- Added permissions for roles to choose a layout from the layout library
- 11/26
- medium
1. clear cache & `drush cim`
1. verify contributor users dont see the layout choices on the basic page but site managers do see the select list.

D8CORE-826 layout library perms

---

composer.json
config/sync/config_split.config_split.dev.yml
config/sync/config_split.config_split.prod.yml
config/sync/config_split.config_split.stage.yml
config/sync/core.extension.yml
stanford_profile.info.yml

- Enable `seckit` at install time
- January 13, 2020
- How critical is this PR on a 1-10 scale? 7
- ISO wants it
1. See https://github.com/SU-SWS/acsf-cardinalsites/pull/48
- D8 Core
- JIRA ticket: D8CORE-580
- Other PRs: https://github.com/SU-SWS/acsf-cardinalsites/pull/48

D8CORE-580: HSTS

---

config/sync/user.role.site_builder.yml
config/sync/user.role.site_editor.yml
config/sync/user.role.site_manager.yml

- Non-administrator roles (Site Manager, Site Editor, Site Builder) have the "See environment indicator" permission. This is probably not useful for non-SWS users. (We don't want to give end-users the impression that they have dev/test environments.)
- ?
- Low
2. Do a build
3. Log in as each of the roles without environment detection
4. Confirm they don't have it.
- Launch
- D8CORE-875
- @jbickar 

D8CORE-875: Remove env indicator permissions from roles

---

stanford_profile.profile
tests/behat/features/Users/Roles.feature

- Prevent the home page, 404, and 403 nodes from being deleted.
- 1/29
- medium
1. clear caches
1. log in as a site manager
1. Attempt to delete the 404, 403, or home page.
1. validate you aren't able to do so.

D8CORE-1200 Prevent home page from being deleted

---

config/sync/crop.type.focal_point.yml
config/sync/filter.format.stanford_html.yml

- Allow classes on header elements to allow the user to center them.
- also see https://github.com/SU-SWS/stanford_text_editor/pull/12
- 1/29
- low
1. checkout branch
1. drush cim
1. create a page with a wysiwyg
1. add some text and make it an `h3`
1. validate you can center that text.

D8CORE-1013 Allow classes on header elements

---

config/sync/filter.format.stanford_html.yml
tests/behat/assets/documents/WYSIWYG.html
tests/behat/features/Paragraphs/WYSIWYG.feature

- Removes h6 from the options in the format bar in wysiwyg
- Jan 29th
- Low
2. Install site or import config (or manually edit the setting in the ui)
3. Clear cache
4. Review format drop down in wysiwyg editor on stanford_page wysiwyg component
- D8CORE
- D8CORE-1153
- github.com/SU-SWS/stanford_text_editor/pull/13

D8CORE-1153: Remove h6 from stanford_text formats

---

config/sync/simplesamlphp_auth.settings.yml

- added missing setting in simplesamlphp_auth.settings config
- 2/12
- medium
see https://github.com/SU-SWS/stanford_basic/pull/124
https://github.com/SU-SWS/stanford_ssp/pull/83
https://github.com/SU-SWS/stanford_basic/pull/124

D8CORE-1024 Added missing config setting for simplesamlphp_auth

---

config/sync/responsive_image.styles.card_2_1.yml

- Card image was not filling out the container at the MD breakpoint on interior pages.
- Feb 12th
- Low
1. Put a card on an interior page and resize your browser until you see the whitespace gap
2. Check out this branch and import config (drush cim)
3. Clear caches and re-test the interior page to see gap-b-gone
- Everywhere card is used
- D8CORE-1234
- Totally got ticket 1-2-3-4! woot.

D8CORE-1234: Add missing breakpoint for 2:1 card responsive image style.

---

content/paragraph/5395f779-e884-4429-a533-a6712bd4eb32.json

- Change default content to support mo' betta user workflow
- v1.0.0
- How critical is this PR on a 1-10 scale? 7/10
- It's the front door of our product
2. Install this profile
3. Check that banner looks like this:
4. Check that the hyperlink sends you to SAML login
- D8CORE
- JIRA ticket: D8CORE-1289

D8CORE-1289: Update homepage banner default content

---

composer.json
config/sync/block.block.stanford_basic_pagetitle.yml
config/sync/core.extension.yml
tests/behat/features/BasicPage.feature

- Added response code condition to hide title block on 404 and 403 pages
- 2/28
- high
1. `composer require su-sws/dev-D8CORE-1393`
1. `blt drupal:update`
1. navigate to any url that doesnt exist
1. validate only 1 page title
1. enter something in the search field at the top
1. validate the search page has a page title.

D8CORE-1393 Dont display page title block on 404 and 403 pages

---

modules/stanford_profile_styles/stanford_profile_styles.libraries.yml

- stanford_media css changes the media library icon. but react widgets don't load that css outside the ckeditor iframe. so we add it to the form level.
- 2/28
- medium
1. clear cache
1. create/edit a basic page
1. add a text area paragraph and verify the media library icon doesn't contain a musical note.

Added stanford media library to node form since react doesnt add it

---

config/sync/editor.editor.stanford_html.yml
src/Plugin/InstallTask/RouteRebuilder.php
tests/src/Kernel/Plugin/InstallTask/RouteRebuilderTest.php

- Use drupal cores link buttons for now so that media images can be linked.
- Rebuild node access on install.
- asap
- high.
1. `drush cim`
1. create a page with a wysiwyg and add an image
1. validate you can add a link to the image.

D8CORE-1340 Use core link in wysiwyg for now

---

config/sync/core.entity_view_display.config_pages.stanford_local_footer.default.yml

- Removes limits on rendered url string
- Thursday
- Medium. 
1. In you rdefault 1.x build of cardinalsites enter a url that is longer than 80 characters into the action field of the local footer
2. Clear cache and inspect form action url. 
3. See it truncated and shows `...` 
4. Check out this branch and import config
5. Clear cache and see full url in action field.
- D8CORE
- Related: https://github.com/SU-SWS/jumpstart_ui/pull/38

D8CORE-1451: Do not limit url characters in local footer

---

composer.json
stanford_profile.profile

- Removes warning label and fields from form page where some items were editable and others were not.
- Feb 26th
- Med/Low
1. Do a full site build with stanford_profile
2. Check out this branch and clear cache
3. Set `$settings['config_readonly'] = TRUE;` in your `local.settings.php` file.
4. Log in as a site_manager and edit the form at `/admin/structure/menu/manage/main`
5. Log in as an administrator and edit the form at `/admin/structure/menu/manage/main`
- D8CORE
- D8CORE-1370

D8CORE-1370: Alter menu form and status messages for config_readonly users

---

config/sync/ds.field.su_site_name.yml

- Changes filter format to `minimal` to allow for html entities 
- Currently, htmlentities are encoded and passed into the twig templates rendering `&` as `&amp;`
- Thursday
- Medium/Low
1. Set the site name to `Tom & Jerry`
2. Clear cache and review the local footer lockup
3. See double encoding of the `&`
4. Check out this branch and import config
5. Clear cache and see only once encoding of the `&`
6. Jen is working on fixing the twig template to handle the second encoding. 
- D8CORE-1327
- D8CORE-1327
- FYI @jenbreese 

D8CORE-1327: Change filter-format to allow for html entities.

---

content/menu_link_content/26a314fe-33aa-4660-b06a-97b26dc75baf.json
stanford_profile.info.yml

- Set the node to be the home menu link: this displays the link info on the node form
- removed line of paragraph uuid that was removed.
- :man_shrugging: 
- low
1. run a fresh install
1. on the home page click edit
1. validate the menu setting on the node show that it is in the menu.

Set home link to the home node for default content

---

composer.json

- TL;DR - `views_bulk_operations` introduced an upgrade-path bug in version 3.4, which was causing problems completing a `drush updb`.  This was fixed with the 3.6 release, which was published this morning. Locking the version called for in the profile to 3.6 and above prevents us from being affected by the bug.
- By the 1.0.1 release
- This bug affects the upgrade path, and may interfere with stack upgrades going forward.
1. Install the stack with this updated requirement.
2. Check to make sure that `drush updb` completes correctly
3. Check to make sure that `views_bulk_operations` still works as expected.
- This may affect views which set action preliminary configurations.  Those configurations would be dropped with the unmodified 3.4 upgrade, but will be preserved with this update.
- …

D8CORE - bumping version of `views_bulk_operations`

---

config/sync/user.role.site_manager.yml

- Allows site_managers to grant site_managers
- March 10
- Low
2. Install new site or import config
3. Log in as a site_manager and navigate to the user page
4. Assign a lower level user the site_manager role
- D8CORE
- D8CORE-1471
- D8CORE-1473

D8CORE-1471: Allow site_manager to assign the site_manager role.

---

tests/behat/features/BasicPage.feature

- the step definition doesn't exist. use one that does
- the tests before weren't failing if a step definition was undefined. they do now.
- asap
- medium
1. review test results and https://circleci.com/gh/SU-SWS/acsf-cardinalsites/2741?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
looks like previous tests didnt get marked as failure https://circleci.com/gh/SU-SWS/stanford_profile/1648?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

use an existing step definition

---

composer.json
tests/behat/features/Paragraphs/Issue2901390.feature

- Fixed error when trying to save a custom block in the layout builder.
- patch added to the stack in https://github.com/SU-SWS/acsf-cardinalsites/pull/117
- 3/19
- high
1. Checkout https://github.com/SU-SWS/acsf-cardinalsites/pull/117
1. Create a basic page
1. edit the layout for that page
1. add a custom block
1. when saving validate it doesn't throw an error.

D8CORE-1689 Allow custom blocks in layout builder

---

modules/stanford_profile_styles/stanford_profile_styles.module

- Fixed adding styles to a page that isn't a stanford_page
- soon
- medium
1. create a new content type. no need to add any fields and all other default settings.
1. create a piece of content from that new content type
1. try to view and verify you can view the node page.

add stanford_page_layout_full only to stanford pages

---

composer.json
config/sync/config_split.config_split.dev.yml
config/sync/config_split.config_split.local.yml
config/sync/config_split.config_split.prod.yml
config/sync/config_split.config_split.stage.yml
config/sync/core.extension.yml

- seckit was enabled for all split, so lets move it to the core.extension.yml
- whenever
- low
1. `composer require su-sws/stanford_profile:dev-require-devs`
1. `composer require drupal/devel:^2.0 drupal/devel_php:^1.0 --dev`
1. `blt drupal:install`
1. validate local still installs with no error.

fixed seckit split

---

config/sync/core.menu.static_menu_link_overrides.yml
config/sync/user.role.site_manager.yml
tests/behat/features/BasicPage.feature

- Disables: "Run Updates" & "Delete orphaned composite" from admin toolbar menu
- The next release would be nice.
- Low
1. Run an install or `drush cim` to get the latest
2. Validate that the menu items are disabled in the administration menu.
- D8CORE
- D8CORE-1708
- D8CORE-1707

D8CORE-1708 D8CORE-1707: Disable menu items in toolbar.

---

composer.json
config/sync/core.extension.yml
config/sync/editor.editor.stanford_html.yml
stanford_profile.info.yml
tests/behat/features/DefaultContent.feature

- Adds the accessibility checker to the ckeditor wysiwyg
- SEE: https://github.com/SU-SWS/acsf-cardinalsites/pull/134 
- April 7th
- Low
1.  SEE: https://github.com/SU-SWS/acsf-cardinalsites/pull/134
2. Review code.
- D8CORE
- D8CORE-1792
- D8CORE-1490

D8CORE-1792: Enabled a11y_checker for text editor.

---

.circleci/config.yml
.github/workflows/tag_commits_to_master.yml
README.md
composer.json
tests/behat/features/Paragraphs/WYSIWYG.feature

- Changed composer to use @dev versions of su-sws packages, added tag_commits_to_master github action, updated readme.
- This PR establishes the `8.x-1.x` branch as our development branch, and changes the release process.
- The new process is to cut a release branch from the latest commit on `8.x-1.x` branch.  Then, update the composer.json file to require the latest tagged versions of the SU-SWS packages, eliminating the `@dev` dependencies.  Then, open a PR to merge the release branch to `master`.  Upon a successful merge to `master`, a new tag will be created to bump the semver here by 1 patch increment.  If you wish to bump it by a minor or major version, include the text `#minor` or `#major` in the PR for the release branch.
- for 1.1.0 release
- Medium.
1. Use this branch in your …

D8CORE-1664

---

config/sync/core.entity_form_display.media.google_form.default.yml
config/sync/core.entity_form_display.media.google_form.media_library.yml
config/sync/core.entity_view_display.media.google_form.default.yml
config/sync/core.entity_view_display.media.google_form.media_library.yml
config/sync/field.field.media.google_form.field_media_google_form.yml
config/sync/field.storage.media.field_media_google_form.yml
config/sync/media.type.google_form.yml
config/sync/seckit.settings.yml

- this is dependent on https://github.com/SU-SWS/stanford_media/pull/49
- New media type for google forms
- 4/15
- medium
1. checkout the branch in stanford_basic
1. clear cache
1. a page with a wysiwyg and add a google form.
1. validate it embeds.

D8CORE-1197 Added google form media type

---

composer.json
modules/stanford_paragraph_card/stanford_paragraph_card.module
tests/codeception/acceptance/Paragraphs/StanfordCardCest.php

- Decode html entities and quotes when the Display Suite cloned field is used.
- I have a feeling this is going to happen often.
- first commit in this PR was the test alone. following commits resolved the test.
- 4/22
- high
1. create a card and for the link text put some quotes in.
1. choose "Button" for the link style
1. Save and verify the quotes look correct
1. change the button style to action
1. verify the quotes still look correct

D8CORE-1847 fix link text getting encoded

---

config/sync/linkit.linkit_profile.default.yml
tests/codeception/acceptance/MediaCest.php

- Add file media bundles to linkit autocomplete
- 4/29
- medium
1. go to a wysiwyg and upload a pdf or word doc or something via the media library
1. don't "insert" the media
1. highlight some text and click the link button
1. start typing the name of your file and click the suggestion
1. save the page and validate the path to the file is correct on the link.

D8CORE-1458 Add media to linkit suggestions for inline links

---

composer.json
config/sync/core.entity_view_display.node.stanford_page.default.yml
config/sync/core.extension.yml
config/sync/node.type.stanford_page.yml
config/sync/node_revision_delete.settings.yml
tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php

- Setup node revision delete module and configuration
- 4/29
- medium
1. `composer require su-sws/stanford_profile:dev-D8CORE-1852`
1. create a node and edit it at least 5 times to generate the different revisions
1. `drush cron`
1. verify you are left with 5 revisions on the node

D8CORE-1852 Setup node revision delete on stanford_page

---

config/sync/field.field.config_pages.stanford_saml.su_simplesaml_roles.yml
config/sync/simplesamlphp_auth.settings.yml
config/sync/stanford_ssp.settings.yml

- Fix misspelled eduPersonEntitlement
eduPersonEnttitlement => eduPersonEntitlement
Might also need to update user guide:
https://userguide.sites.stanford.edu/tour/site-organization-menus/managing-user-accounts/how-add-workgroup-role-mapping

Fix misspelled eduPersonEntitlement

---

composer.json
config/sync/core.extension.yml
config/sync/layout_library.layout.stanford_basic_page_full.yml
stanford_profile.post_update.php

- Added stanford_notification module and add notification for news and person
- tomorrow
- high
1. checkout `8.x-1.x` branch and install a site and create/edit a site manager or contributor 
1. then `composer require su-sws/stanford_profile:dev-notification-module`
1. `blt drupal:update`
1. disable saml so you can log in as a site manager or contributor
1. view the site as an existing site manager or contributor
1. verify there are 2 new notifications for the user.

Added stanford notifications module

---

config/sync/field.field.node.stanford_news.su_news_headline.yml
config/sync/field.storage.node.su_news_headline.yml

- Changed max chars on headline field
- Asap
- High
1. Check out this branch and do a `drush cim` or a full install
2. Validate that the headline field on news items is 180 chars and not 70.
- D8CORE
- https://github.com/SU-SWS/stanford_news/pull/79

D8CORE-000: Changed headline on news to 180 max from 70.

---

config/sync/core.entity_form_display.node.stanford_page.default.yml
config/sync/field.field.node.stanford_page.su_page_components.yml
stanford_profile.post_update.php

- Sets all react paragraphs to max of 3 in a row.
- Adds notification to all user types for max-of-3
- ASAP
- Today
1.  Check out this branch
2. Import config
3. Try to place items more than 3.

D8CORE-000: Set media with caption and wysiwyg to 3 in a row.

---

config/sync/field.field.paragraph.stanford_card.su_card_body.yml

- Changing the label on the card paragraph's wysiwyg field
- 5/21/2020
- low
1. Install stanford_profile using this branch and verify label is: "Description"
- card authoring on stanford card
- D8CORE-2038: Card authoring: change "Body" label to "Description" for the markdown field

changed label from body to description on card

---

stanford_profile.profile
tests/codeception/acceptance/Contrib/XmlsitemapCest.php

- Removing 403 and 404 pages from xmlsitemap
- ???
- low
1. on a build of lelelandd8 using soe_profile rebuild the xmlsitemap and verify the 403 and 404 pages are not in it.
- soe_profile and associated sites
- https://stanfordits.atlassian.net/browse/D8CORE-2153
- https://stanfordits.atlassian.net/browse/D8CORE-1989

remove 403 and 404 from xmlsitemap

---

composer.json
config/sync/core.extension.yml
config/sync/page_manager.page_variant.people-layout_builder-0.yml
config/sync/user.role.site_builder.yml
config/sync/user.role.site_developer.yml
config/sync/user.role.site_manager.yml
config/sync/views.view.su_block_edit_links.yml
tests/codeception/acceptance/Content/CustomBlockCest.php

- Allow site managers access to edit custom blocks.
- asap
- high
1. `composer require su-sws/stanford_profile:dev-D8CORE-2220`
1. `drush cim -y & drush pmu simplesamlphp_auth & drush uli Morgan`
1. go to `/people` page and verify you can click the link and edit the intro block.

D8CORE-2220 Site managers can edit custom blocks

---

config/sync/core.entity_view_display.node.stanford_event.default.yml
config/sync/views.view.stanford_events.yml

- Fixed the logic in event views when there isn't an external url.
- Re-ordered event fields on the node display to keep fields matching
- also see https://github.com/SU-SWS/stanford_events/pull/7
- asap
- critical
1. checkout this branch & import config
1. create an event without an external source url
1. view it on the event list page and verify it's title with link still displays

Fix missing event title in views and re-ordered event node fields

---

config/sync/views.view.stanford_news.yml

- added the See More News to the vertical cards.
- Thursday
- Medium
1. Pull in this change
2. Get the configuration change from profile.
3. Refresh the css.
4. Verify on the sample news article at the bottom o
- D8Core-2292 in News module and in the Profile module.
- D8Core-2292
- https://github.com/SU-SWS/stanford_news/pull/87
- https://github.com/SU-SWS/stanford_profile/pull/239

D8CORE-2292: Added in the More news button

---

composer.json
config/sync/config_ignore.settings.yml
config/sync/core.extension.yml
src/Config/ConfigOverrides.php
stanford_profile.profile
stanford_profile.services.yml
tests/codeception/acceptance/SubThemeCest.php
tests/src/Unit/Config/ConfigOverridesTest.php

- Configure config_ignore module to allow for custom themes
- 6/25
- medium
1. use the branch in https://github.com/SU-SWS/acsf-cardinalsites/pull/162 and do a `composer install`
1. To test with config readonly enabled, comment out the Acquia environment conditions in the `global.settings.php`
1. install a fresh site or use an existing one and import config
1. create any stubbed out sub theme based on stanford_basic. you only need the `info.yml` file
1. enable the subtheme via drush `drush then [theme_name]`
1. go to the appearance page and enable the theme
1. edit the theme settings
1. run a config import and validate nothing moves with the new theme.

D8CORE-2205 Configure config ignore to allow for custom theme enabling

---

config/sync/core.entity_form_display.node.stanford_news.default.yml
config/sync/field.field.node.stanford_news.su_news_publishing_date.yml
config/sync/field.field.node.stanford_news.su_news_topics.yml
config/sync/views.view.stanford_news.yml

- 2178: Set paragraphs to collapsed by default
- 2180: Add help text to topics field that links to userguide page
- 2181: Alter the view sorting so that it sorts on published date rather than authored date
- June 30th
- Medium 
2. Import config (drush cim)
3. Go to create a new news node and see default date on publishing date is today 
4. On new news node form see new help text on topic field that links to userguide page
5. Fill out the fields and save the news node
6. Create one or more news nodes with different dates
7. Navigate to /news and validate that the sorting is in the correct order
- D8CORE
- SOE
- D8CORE-2178
- D8CORE-2180
- D8CORE-2181
- @cynmij 
- https://github.com/SU-SWS/stanford_news/pull/89
- [PR …

D8CORE-2178, D8CORE-2180, D8CORE-2181: Event updates

---

config/sync/views.view.stanford_events.yml

- Removing the su-link--action on the Event list pages. If the link goes to a node, there doesn't need to be the right arrow.
- Soonish
- Med
2. Navigate to Events.
3. Verify Event List pages (filtered and not) with a Node page doesn't have the > on the link. It should also not appear on the Event-Series page as well. 
- Core Product
- D8CORE-2318
- https://github.com/SU-SWS/stanford_profile/pull/245
- https://github.com/SU-SWS/stanford_events/pull/14

D8CORE-2318: removing the action arrow on list items

---

config/sync/core.extension.yml

- Removed module from that isn't being used and is no longer part of dependencies.
- asap
- high

Removed views_taxonomy_term_name_depth not in use.

---

config/sync/image.style.square_1192.yml
config/sync/image.style.square_1900.yml
config/sync/image.style.square_478.yml
config/sync/image.style.square_956.yml
config/sync/responsive_image.styles.responsive_1_1.yml

- We want a responsive 1:1 image style. To accomplish that, I created 1:1 image styles following the patterns and dimensions specified in the Card 2:1 responsive image style.  These configs set up the styles and make them available..
- 7/24/2020
- Not critical.
2. Do a `drush cim` to import the configs.
3. Create a page with 3 Card paragraphs.
4. Observe they use the `Card 2:1` images when saved.
5. Visit /admin/structure/paragraphs_type/stanford_card/display
6. Switch the Image or Video widget's Image Style to render as `Responsive 1:1`, and save your changes
7. Visit your page you created in step 3.  Observe the images in the paragraphs are now square.
- n/a
- https://stanfordits.atlassian.net/browse/D8CORE-2155
- [PR …

D8CORE-2155: Added configs for responsive 1:1 image styles

---

config/sync/views.view.content.yml

- Reset selection when the user filters.
- 7/29
- medium
1. import config
1. view `/admin/content`
1. select some rows in the view
1. filter the results to another content type
1. validate the selection has been cleared.

CSD-258 Reset selection when filtered

---

config/sync/filter.format.stanford_html.yml

- Added html pre tag to allowed html tags.
- whenever 
- super low
1. Pull this branch
2. Clear cache
3. Create a basic page and add this snippet in the text area source and save:
```
<pre>
<code lang="css">
/* Stanford Web Services 
:D */
body {
display: block;
}
</code>
</pre>
```
The spacing/line breaks should stick and look something like this:
- Dev Guide Sub Theming for Code Snippets
- https://github.com/SU-SWS/stanford_text_editor/pull/37

DEVGUIDE-000 Added html pre tag to allowed html tags.

---

config/sync/field.storage.config_pages.su_lockup_options.yml
tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php

- Allow for Decanter's M option.
- Sept 2nd
- Med/Low
2. Clear cache
3. Go to lockup setting form
4. Select Option M
5. See only fields for line 1 & line 2
6. Fill in those fields and save
7. See rendered out fields on home page.
- D8CORE 
- VPSA
- EARTH
- Others
- D8CORE-2591

D8CORE-2591: Allow lockup option M

---

config/sync/views.view.stanford_person_list_terms_first.yml

- Changed sorting on interior people pages to sort by last name then first name
- Sept 3rd?
- 3/10
2. Check out branch D8CORE-2535 of the stanford_person module
3. Import config (drush cim)
4. Clear all caches
5. Ensure sort order is correct by creating and placing a few sample profiles in a group

D8CORE-2535: Changed sort fields on people term pages

---

stanford_profile.post_update.php

- Adds global message and super footer blocks to sites with custom themes.
- Friday Sept 11th
- Hight
1. On an existing build clone down a new theme (https://github.com/su-sws/saa_victoria_subtheme/) into /docroot/themes/custom
2. Enable the theme and set as default
3. Remove the global message and super footer blocks if they were placed in the block system
4. Check out this branch
5. Run database updates
6. Validate blocks were placed.
- SAA sites only
- No Jira tickets
- @buttonwillowsix 
- @katrialesser 
- @alisonho 

D8CORE-000: Custom theme blocks for custom sites with custom themes.

---

config/sync/core.entity_form_display.node.stanford_person.default.yml
config/sync/core.entity_view_display.node.stanford_person.default.yml
config/sync/core.entity_view_display.node.stanford_person.teaser.yml
config/sync/field.field.node.stanford_person.su_person_academic_appt.yml
config/sync/field.field.node.stanford_person.su_person_admin_appts.yml
config/sync/field.field.node.stanford_person.su_person_scholarly_interests.yml
config/sync/field.storage.node.su_person_academic_appt.yml
config/sync/field.storage.node.su_person_admin_appts.yml
config/sync/field.storage.node.su_person_scholarly_interests.yml
config/sync/migrate_plus.migration.su_stanford_person.yml
tests/codeception/acceptance/Content/PersonCest.php
tests/codeception/acceptance/LocalFooter/LocalFooterCest.php

- Added 3 new fields (hidden on form and display until designs are available)
- Changed the importer to populate 4 fields
- Changed the importer to not create revisions. this appeared to be causing some issues and I hope that it will resolve some of them.
- 9/21
- low
1. import config
1. import profiles (i've been using org code `QYIS`)
1. load one of the profiles with devel and see the populated data.
- https://github.com/SU-SWS/stanford_person/pull/110

CAP-52 Import 3 more fields from the API

---

config/sync/views.view.stanford_person.yml

- Matching the person edit button to the news edit button
- 9/25
- Low
- Effects all the sites with a people grid page. It is only on the authoring environment button.
2. Navigate to the person grid page while logged in.
3. Review the edit button and verify it matches the news one.
- Person pages in edit mode
- D8CORE-2185
- https://github.com/SU-SWS/stanford_person/pull/113
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/Exter …

D8CORE-2185: matching the person edit to the news edit

---

config/sync/migrate_plus.migration.su_stanford_person.yml
tests/codeception/acceptance/Content/PersonCest.php

- Use the new process plugin in https://github.com/SU-SWS/stanford_migrate/pull/15
- 10/15
- medium
1. checkout this branch & related branch in https://github.com/SU-SWS/stanford_migrate/pull/15
1. using a profile that doesn't have a public image use the sunet and import that profile
1. validate the profile isn't imported with a black dot image.

D8CORE-2470: Add process plugin to check image dimensions

---

config/sync/migrate_plus.migration.su_stanford_person.yml

Before:
1. Importer runs and imports the image, lets say `pookmish123456.jpg` with file id `8` (123456 is the timestamp from the API)
1. a user changes the image and now its `pookmish654321.jpg` with file id `15`
1. the importer will run again and the file doesn't exist on the server so it downloads it
1. When getting to the `entity_generate` step, the key was targeting the name of the media item so it searches for the media entity before generating a new entity. Since the media item already exists, it doesn't create a new media item for the `pookmish654321.jpg`
1. The profile isn't updated with the new image
After:
In step 4 from above, now the entity_generate will search for a media item based on the file id of the imported file. Since no media item contains the file id `15` it will …

Adjusted the person importer to update the media item correctly

---

config/sync/core.entity_form_display.node.stanford_person.default.yml
tests/codeception/acceptance/Content/PersonCest.php

- Takes the config changes here: https://github.com/SU-SWS/stanford_person/pull/121
and applies them to the profile.
- soon.
- not critical
- Check out this branch
- `drush cim`
- Make a Person content type.
- in the "Interests & Affiliations" field group, add a link under Links or Stanford Affiliations.
- Notice that when you put in a URL, the Link Text gets marked as required.
- Notice that the "Interests & Affiliations" field group as a whole does not get marked as required.
- https://stanfordits.atlassian.net/browse/D8CORE-2002
- https://github.com/SU-SWS/stanford_person/pull/121

D8CORE-2002: config adjustment to hide required asterisk for field group

---

composer.json
config/sync/core.extension.yml
config/sync/views.view.stanford_news.yml
tests/codeception/acceptance/Paragraphs/ListsCest.php

- Added contextual filter arguments for the news topic terms
- 10/30
- medium
1. drush cim
1. create some news with topic terms associated to them
1. create a basic page with a "Lists" paragraph using either of the news views.
1. Populate the "Arguments" with the taxonomy term names.
- Note that if you populate it with a string that doesn't correlate to a taxonomy term name, the arguments will be empty and therefore it won't filter the content at all. It will be as if you didn't put any arguments in at all.
1. validate the view is filtered for your content.

D8CORE 2710 News lists contextual filters and tests

---

composer.json
config/sync/core.extension.yml
config/sync/views.view.stanford_person.yml
tests/codeception/acceptance/Paragraphs/ListsCest.php

- Added contextual filter arguments for the People Type terms
- 10/30
- medium
1. drush cim
1. create some profiles with "Type" terms associated to them
1. create a basic page with a "Lists" paragraph using the people views.
1. Populate the "Arguments" with the taxonomy term names.
- Note that if you populate it with a string that doesn't correlate to a taxonomy term name, the arguments will be empty and therefore it won't filter the content at all. It will be as if you didn't put any arguments in at all.
1. validate the view is filtered for your content.

D8CORE-2885 People lists contextual filters and tests

---

config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
config/sync/ds.field.news_content_url.yml
config/sync/views.view.stanford_news.yml
tests/codeception/functional/Paragraphs/EntityReferenceCest.php

- Configure the card display mode on news to use the vertical teaser pattern
- Change the views to use the view mode instead of fields for consistency.
- 10/30
- medium
1. checkout this branch & the matching branch in https://github.com/SU-SWS/stanford_news/pull/103
1. `drush cim`
1. Create a news item or publish existing news content.
1. create a basic page
1. add a "Content Reference" paragraph type
1. In the content reference field choose a news item
1. save the page and verify the news card looks like the vertical card pattern.

D8CORE-2720 D8CORE-2787 News card display for entity reference

---

config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml

- Changed card display mode to prevent nested `<h2>` tags.
- Changed card display mode to use responsive square image style which will make a circle.
- 10/30
- medium
1. Checkout this branch & same branch in https://github.com/SU-SWS/stanford_profile_helper/pull/40
1. create a person with an image
1. create a basic page and reference that person in the paragraph type
1. verify the image is a circle centered in the card.

D8CORE-2780 Use square image style to make a circle

---

config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
config/sync/core.entity_view_display.paragraph.stanford_entity.default.yml
config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml
config/sync/views.view.stanford_events.yml
config/sync/views.view.stanford_news.yml

- some minor adjustments to the card display modes to make use of the utility classes in https://github.com/SU-SWS/stanford_profile_helper/pull/42
- Added a specific "Cards" view that only shows 3 items.
- see https://github.com/SU-SWS/stanford_profile_helper/pull/42
- 11/4
- medium
1. checkout this branch and https://github.com/SU-SWS/stanford_profile_helper/pull/42
1. drush cim
1. create a basic page and use the list and content reference paragraphs.
1. populate all the fields on the paragraphs.
1. see some of the spacing is applied to the display.

D8CORE 000 display tweaks

---

content/paragraph_row/0427d80b-1f0a-43e1-b902-03d7df3d8523.json
content/paragraph_row/27047c34-f161-45d4-ab65-c7d7c0e98765.json
content/paragraph_row/4a607606-12f6-482c-8cd7-a57d64aeff6b.json
content/paragraph_row/71b78295-dfd1-4eb3-8d20-2013d5b64f69.json
content/paragraph_row/8f739f14-a899-4880-9c11-5929f0d4ddde.json
content/paragraph_row/95514879-c3d0-44cc-a8bd-987f547fa1a8.json
content/paragraph_row/a9a54e9d-e433-408f-be3d-141d3cb3aad6.json
content/paragraph_row/b9027856-bb49-4c3b-9367-87a4e3731421.json
content/paragraph_row/ec2d0801-e418-4bec-a1f9-064c349148d7.json
content/paragraph_row/ed135145-45ed-4955-a1b6-1141bc869568.json
tests/codeception/acceptance/Paragraphs/ListsCest.php

- Updated the default content since the `behavior_settings` are serializable arrays now
- asap
- high
1. checkout this branch and the latest `8.x-2.x` from `react_paragraphs`.
1. `blt di -n`
1. validate it installs.

Updated default content for the paragraph row serializable data

---

config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml
config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
config/sync/views.view.su_block_edit_links.yml
content/block_content/5168834f-3271-4951-bd95-e75340ca5522.json
content/block_content/f7125c85-197d-4ba2-9f6f-1126bbda0466.json
tests/codeception/acceptance/Content/EventsCest.php
tests/codeception/acceptance/Content/NewsCest.php
tests/codeception/acceptance/Paragraphs/ListsCest.php

- Add intro blocks at the top of events and news list pages.
- Update hook: https://github.com/SU-SWS/stanford_profile_helper/pull/45
- 11/5
- medium
1. checkout this branch.
1. either do a fresh install, or checkout the same branch in [stanford_profile_helper](https://github.com/SU-SWS/stanford_profile_helper/pull/45) and do a `blt drupal:update`
1. Go to the news and the events pages
1. click on the link to edit the intro block
1. populate it with stuff
1. validate it displays at the top of the page.

D8CORE-2570 Add intro block above event and news lists

---

config/sync/user.role.site_manager.yml

- Allow site managers access to contextual links so they can configure and delete blocks in the layout builder.
- asap
- high.
1. `drush cim`
1. log in as a site manager
1. verify you can delete a block from layout builder on a basic page.

D8CORE-2864 Allow site managers access to contextual links

---

config/sync/editor.editor.stanford_minimal_html.yml

- Changed the link button in minimal html to be the link button from core instead of the anchor link module.
- 12/3
- low
1. create a basic page and add a card
1. verify the link button in the ckeditor modal is the same as the other wysiwygs from other paragraph types.

D8CORE-2495 Changed the link button in minimal html format

---

composer.json
tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php

- Patched the diff module to display all revisions of content.
- 12/3
- medium
1. download the [patch](https://www.drupal.org/files/issues/2020-09-11/2882334-diff-missing_some_revisions-11.patch) and apply it to the `diff` module
1. create/edit a node and make some changes to the fields (don't change the node title)
1. view the revisions page for the node and validate you see your new revision.

D8CORE-2759 Fix revisions table to show all revisions

---

config/sync/imagemagick.settings.yml

- Added support for animated gif's resizing.
- 12/3
- medium
1. Download [this gif ](https://students.alumni.stanford.edu/sites/g/files/sbiybj16871/files/media/image/stanfordstudents_0.gif?itok=dgY1dSfA)
1. create a basic page and use the gif you download. set it to display the `large` or smaller display
1. see the broken gif.
1. `drush cim` & `drush if --all`
1. view the page again and verify the gif isn't broken anymore.
Broke:

D8CORE-2878 Add coalesce support for small animated gif fix

---

config/sync/views.view.stanford_events.yml
config/sync/views.view.stanford_news.yml
config/sync/views.view.stanford_person.yml
tests/codeception/acceptance/Paragraphs/ListsCest.php

- Display content that have taxonomy terms as children of the entered arguments.
- 12/3
- medium
1. create a couple of people/news/events
1. tag them with parent and child taxonomy terms
1. create a basic page using the list paragraph type
1. enter the parent taxonomy term as the arguments for the view
1. verify the content with the parent and the child terms display in the list.

D8CORE-3051 Allow paragraph views to display nested taxonomy content

---

composer.json

- Fixes the redirect the next day.
- 12/3
- medium
1. apply the patch manually or `composer require su-sws/stanford_profile:dev-D8CORE-000-saml-patch`
1. log into your local with saml.
1. navigate to a page like `/events`
1. see you are still logged in and on that url still.
1. edit the file `docroot/modules/contrib/simplesamlphp_auth/src/EventSubscriber/SimplesamlSubscriber.php` and comment out part of the code as in the screenshot below.
1. reload your `/events` page
1. verify you stayed on that page and are logged out.

D8CORE-000 Patch simplesamlphp auth module to prevent unwanted redirect

---

config/sync/core.entity_view_display.node.stanford_event.default.yml

- A simple config change to add a separator for date strings.
- see related PR in stanford_events: https://github.com/SU-SWS/stanford_events/pull/44
- Dec. 3
- 1 of 10
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs

D8CORE-2325: fixed separator between event dates

---

config/sync/config_ignore.settings.yml
config/sync/metatag.metatag_defaults.node__stanford_news.yml
config/sync/metatag.metatag_defaults.node__stanford_person.yml
config/sync/rabbit_hole.behavior_settings.default.yml
config/sync/rabbit_hole.behavior_settings.default_bundle.yml
config/sync/rabbit_hole.behavior_settings.node_type_stanford_event.yml
config/sync/rabbit_hole.behavior_settings.node_type_stanford_news.yml
config/sync/rabbit_hole.behavior_settings.node_type_stanford_person.yml
config/sync/stanford_basic.settings.yml
tests/codeception/functional/Paragraphs/WYSIWYGCest.php

- Fixed the metadata tags for news and people
- exported config after a database update.
- 12/3
- medium
1. create a news item with a featured image
1. view the source and verify the `og:image` tag is visible with the path to the image
1. create a person with a photo
1. view the source and verify the `og:image` tag is visible with the path to the image

D8CORE-2867 Update image metadata tags

---

config/sync/core.entity_view_display.block_content.stanford_component_block.default.yml
config/sync/field.field.block_content.stanford_component_block.su_component.yml

- Adding spacing at the bottom of the new info block on Events, News and People
- Limited the components available to this block after speaking with Ishi. That is covered in D8CORE-3188.
- 1/3/21
- Med
1. Pull in this and the other stanford_profile_helper change.
2. Clear caches
3. Checkout the padding on the new intro content on the New, People, Events List page. 
4. Try adding some content. We will be writing some documentation on best practices since it is currently an open slate. 
5. Try removing the content and see that there is not extra space above the list. 
- Stanford Basic and  SOE
- D8CORE-3142
- D8CORE-3188
- https://github.com/SU-SWS/stanford_profile_helper/pull/60

D8CORE-3142: adding a class to the intro block

---

config/sync/core.entity_view_display.citation.su_article_journal.default.yml
config/sync/core.entity_view_display.citation.su_article_newspaper.default.yml
config/sync/core.entity_view_display.citation.su_book.default.yml
config/sync/core.entity_view_display.citation.su_thesis.default.yml
config/sync/field.field.citation.su_article_journal.su_publisher.yml
config/sync/field.field.citation.su_article_newspaper.su_publisher.yml
config/sync/field.field.citation.su_thesis.su_publisher.yml

- Changed the su-publisher on all the types to be "Publisher"
- Hid some of the fields 
- 2/4
- high
2. import the profile configs.
3. Verify on the publication node that the publisher says "Publisher" for all the types. 
4. Verify the publisher always comes before the date 
- Publication module
- D8CORE-3445
- https://github.com/SU-SWS/stanford_publication/compare/small-tweaks-jbk?expand=1

D8CORE-3445: tweaking the label names and hiding extra fields

---

config/sync/views.view.stanford_publications.yml

- Changing the margin-top class to 1 instead of 3
- 2/11
- Low
1. pull in this change.
2. Pull in the other pull request
3. Refresh
4. verify that the cards on the bottom row of publication node have a margin-top-1 class instead of 3.
- D8CORE-3479
- https://github.com/SU-SWS/stanford_publication/pull/25

D8CORE-3479: changing spacing on more cards

---

config/sync/editor.editor.stanford_html.yml

- Removed "Remove formatting" ckeditor button that does nothing
- 2/25
- low
2. drush cim
3. create a basic page with a wysiwyg.
4. Verify the button doesn't exist. 

D8CORE-1531 Removed "Remove formatting" ckeditor button that does nothing

---

config/sync/views.view.stanford_events.yml
config/sync/views.view.stanford_news.yml

- Changed the order and name of the view blocks so they are in the desired order in the field.
- https://github.com/SU-SWS/react_paragraphs/pull/89
- 2/25
- medium
1. checkout the branch in https://github.com/SU-SWS/react_paragraphs/pull/89
2. checkout this branch
3. drush cim -y
4. create a basic page and add a list paragraph to a row
5. choose "Events" and verify the displays are "- Default List -" followed by "Card Grid"
6. Choose news and verify the same as the events.

D8CORE-3392 Changed the view blocks order and names

---

config/sync/core.entity_form_display.taxonomy_term.event_audience.default.yml
config/sync/core.entity_form_display.taxonomy_term.stanford_event_types.default.yml
config/sync/core.entity_form_display.taxonomy_term.stanford_news_topics.default.yml
config/sync/core.entity_form_display.taxonomy_term.stanford_publication_topics.default.yml
tests/codeception/acceptance/Content/EventsCest.php
tests/codeception/acceptance/Content/NewsCest.php
tests/codeception/acceptance/Content/PersonCest.php
tests/codeception/acceptance/Content/PublicationsCest.php

- Hide the published checkbox on terms.
- 3/3
- low
2. drush cim -y
3. edit a taxonomy term
4. verify there isn't the "Published" checkbox. (The permissions to get that to function correctly aren't worth the benefit)

D8CORE-3137 Hide the published checkbox on taxonomy terms

---

config/sync/core.entity_view_display.node.stanford_publication.default.yml
config/sync/field.field.node.stanford_publication.su_publication_citation.yml
config/sync/field.field.node.stanford_publication.su_publication_topics.yml
config/sync/views.view.stanford_publications.yml

- D8CORE-3484 Disable auto creating terms from the node form
- D8CORE-3482 Add button to edit a publication in the lists
- D8CORE-3564 display the publication type above the title instead of the topic term
- D8CORE-3483 link the help text to the user guide
https://github.com/SU-SWS/stanford_profile_helper/pull/76
- 3/3
- medium
2. drush cim -y
3. verify the 4 items above.

D8CORE-3482 D8CORE-3484 Adjustments to publication lists and fields

---

composer.json
config/sync/core.extension.yml
tests/codeception/acceptance/Content/PublicationsCest.php
tests/codeception/functional/Contrib/RedirectImportCest.php

- Added path redirect import module for csv uploads.
- 2/25
- medium
1. `composer require su-sws/stanford_profile:dev-D8CORE-3050 --no-update`
2. `composer update -n`
3. `drush cim -y`
4. test out the importer on `/admin/config/search/redirect/import`

D8CORE-3050 Added path redirect import module

---

config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
config/sync/views.view.stanford_events.yml

- Adjusted the events list and card views to display all the same content in the same way.
see https://github.com/SU-SWS/stanford_events/pull/54
- 2/18
- medium
1. checkout this branch and the corresponding branch in [stanford_events](https://github.com/SU-SWS/stanford_events/pull/54)
3. create some events and view the related events block at the bottom
4. ensure that related events displays the location

D8CORE-3463 Adjust the list and cards displays

---

config/sync/views.view.publication_terms.yml

- Removed the margin-bottom class on the "Results For" due to too much space.
- 3/3
- low
2. Clear caches.
3. Verify on a filtered Publication page that there is now only MS 3 of space between the first citation and the Results for.
- D8CORE-3576

D8CORE-3576: fixing spacing after the results for on the filtered page

---

config/sync/views.view.publication_terms.yml

This did not fix the problem. There was no problem. The extra space was not present when logged out.
Revert "D8CORE-3576: fixing spacing after the results for on the filtered page"
This reverts commit 6a0c5534aa606f4ef7964ab1ee5bc7c68cadc8cf.
- This change didn't need to happen since the problem didn't exist on a logged out page.
- 3/3
- low
1. Pull in the change.
2. Verify on a logged out filter by page that the Filtered by text has space between content block.
- Publications 
- D8CORE-3576

Revert a previous pull request

---

config/sync/config_pages.type.stanford_basic_site_settings.yml
config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_dropdowns.yml
config/sync/field.storage.config_pages.su_site_dropdowns.yml
tests/codeception/functional/Navigation/NavigationDropDownsCest.php

- Added the drop downs menu setting to the site setting config page.
- tomorrow
- high
3. create a child menu item
4. verify the main menu is not a drop down menu.
5. go to `/admin/config/system/basic-site-settings`
6. check the drop downs checkbox and save
7. go to the home page and verify the dropdown menu is used.

Add a checkbox to the config pages for the drop down menu setting.

---

config/sync/core.entity_form_display.config_pages.stanford_person_importer.default.yml
config/sync/core.entity_view_display.config_pages.stanford_person_importer.default.yml
config/sync/field.field.config_pages.stanford_person_importer.su_person_child_orgs.yml
config/sync/field.storage.config_pages.su_person_child_orgs.yml

- Added checkbox to include child organizations 
- ASAP
- high
1. checkout this branch and the same branch in [stanford_profile](https://github.com/SU-SWS/stanford_person/pull/139)
3. configure the importer with credentials on `/admin/config/importers/person-importer`
4. choose an organization but leave the "include child orgs" checkbox uncheck and save
5. run `drush cget migrate_plus.migration.su_stanford_person source.urls --include-overridden | grep includeChildren` and verify nothing is return
6. now check the box and resave.
7. run the drush command again and verify you see the urls.

Add "include child orgs" checkbox for cap org importer

---

config/sync/views.view.publication_terms.yml

- adding classes to the Filter by in order to style it.
- 3/23
- Med
2. Verify there are classes on the publication filtered page.
3. The css is in the https://github.com/SU-SWS/stanford_publication/pull/32
- As of writing, this isn't ready for merging and review.
- This is the only config change I have related to the Publications.
4. If this [pull](https://github.com/SU-SWS/stanford_publication/pull/32) is added, then you will see the Publications as bold and the font size smaller.  
- Publications
- D8CORE-3947
- D8CORE-3722
- https://github.com/SU-SWS/stanford_publication/pull/32
- @katrialesser 

D8CORE-3947: adding classes to the filtered by for publications 

---

composer.json
config/sync/core.entity_view_display.node.stanford_publication.default.yml
config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
tests/codeception/functional/Paragraphs/EntityReferenceCest.php

- Set up the publications to display as a card in the teasers.
- https://github.com/SU-SWS/stanford_publication/pull/33
- 3/24
- medium
1. `composer require su-sws/stanford_profile:dev-D8CORE-3536 --no-update`
2. `composer update -n`
3. `blt drupal:update` or `blt drupal:install`
4. create a publication and fill out a bunch of fields including at least some citation information and save
5. create a basic page and use the "teaser" paragraph and choose the publication you created
6. save and verify the publication is displayed in a card.

D8CORE-3536 Display publications as a teaser in the paragraph

---

config/sync/views.view.stanford_person_list_terms_first.yml
tests/codeception/acceptance/Content/PersonCest.php

- Changed the filter to only "Published status" instead of the "Published status or admin user" filter.
- 4/7
- low
2. drush cim -y
3. create an unpublished profile and tag it with a person type term
4. view that term list page and verify you don't see the profile you created.

D8CORE-3458 Dont display unpublished profiles in the lists

---

config/sync/views.view.stanford_events.yml

- Added a contextual filter to the past events view.  This will allow filtering by event category in the past events list.
- see also the changes pulled in to the stanford_events module for posterity: https://github.com/SU-SWS/stanford_events/pull/64/files
- 4/7
- medium
2. `drush cim`
3. Create a bunch of past events, with different event types.
4. Create a list paragraph.  Choose the Past Events list.  Under `Advanced`, filter by an event category.  Remember to use dashes to replace spaces.  
5. Verify your list paragraph only shows the past events in the category you specified.
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that …

D8CORE-4033: updated view config to allow filtering past events lists

---

config/sync/filter.format.stanford_html.yml

- Disallow image gallery media in the wysiwyg
- 4/22
- low
1. checkout this branch and `drush cim -y`
2. go to any wysiwyg and click the embed button
3. verify you don't get the option on the left to upload an image gallery.

D8CORE-3480 Disallow image gallery media in the wysiwyg.

---

config/sync/field.field.citation.su_article_journal.su_author.yml
config/sync/field.field.citation.su_article_newspaper.su_author.yml
config/sync/field.field.citation.su_book.su_author.yml
config/sync/field.field.citation.su_other.su_author.yml
config/sync/field.field.citation.su_thesis.su_author.yml
tests/codeception/acceptance/Content/PublicationsCest.php

-  Allow publication authors to have only one name part 
- 4/22
- low
1. checkout this branch and `drush cim -y`
2. create a publication and in the citation information enter only the last name for an author
3. save and verify it does indeed save without errors.

D8CORE-4068 Allow publication authors to have only one name part

---

config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml

- adding styles for the teaser of an Event Series
- 5/5
- Medium
1. Pull in this change
2. Clear caches.
3. Add or make sure you have an Event Series piece of content.
4. Add a teaser of the Series to a page. 
5. Verify the h2 is the right size when put next to another Event teaser.
- SBT - Tested
- SOE - Testing
- SAA - @rebeccahongsf (I tested this too)
- https://github.com/SU-SWS/stanford_profile_helper/pull/106
- https://github.com/SU-SOE/soe_basic/pull/76
- https://github.com/SU-SWS/stanford_profile/pull/409
- D8CORE-3970

D8CORE-3970: removed the extra h2

---

config/sync/views.view.stanford_publications.yml

- This adds the margin bottom to the filtered publications list.
- This fixes the narrow widths when there is little content in a publication.
- This fixes the pagination back to the infinite scroll and Load More button.
- 5/5
- high
1. Pull in this change and clear the caches.
2. Pull in [PR 41](https://github.com/SU-SWS/stanford_publication/pull/41) and clear caches.
2. Go to your publications page and generate 20 + pages.
3. Verify there is a margin bottom.
4. Note the pagination on the filtered pages is known by design. 
- Publications
- [D8CORE-3951](https://stanfordits.atlassian.net/browse/D8CORE-3951)
- https://github.com/SU-SWS/stanford_publication/pull/41

D8CORE-3951: fixing the pagination to the infinite scroll and a Load More button

---

config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml

- Removing the margin top class for the CTA button all the lists. The list objects have padding bottom themselves and it was too much all added up.
- 4/23
- med
2. Clear the caches.
3. Create some lists with and without CTA buttons. Try the default lists and cards.
4. Review the button and see the margin top is removed. 
- Lists module
- Sub themes
- D8CORE-4093
- SOE Subtheme - I tested
- SBT - I tested
- @rebeccahongsf , in case SAA Victoria theme is depending on the button for padding. 

D8CORE-4093: removing the margin top from the button on lists

---

config/sync/core.entity_view_display.block_content.stanford_component_block.default.yml

- Adding margin bottom for the Events Intro paragraph.
- 5/5
- Medium
2. Clear caches.
3. Add an intro to the Events page. This is for the the types that aren't text only.  Such as Banners, Media, etc
- Events for all sub themes. I've test SOE, SAA and SBT.
- [D8CORE-4145](https://stanfordits.atlassian.net/browse/D8CORE-4145)

D8CORE-4145: adding the margin bottom to the intro for events.

---

config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml

- Adding the su-margin-top-5 back to the list button 
- Found an issue with removing it.
- This will undo the work in https://github.com/SU-SWS/stanford_profile/pull/405
- ASAP
- High
1.  Create lists of events in the default view with a set number to display.
2. Notice the button is right up on the line.
3. Pull in this change.
4. Clear caches.
5. Notice the button now has top spacing.  
- List paragraphs
- SAA
- SOE
- SBT
- D8CORE-4215
- D8CORE-4093 (undoing)

D8CORE-4215: Undoing the change to the button margin

---

config/sync/field.field.node.stanford_news.su_news_components.yml
config/sync/field.field.node.stanford_person.su_person_components.yml

- Enable more paragraphs on news and people
- Mirrors the events components field setting
- 5/20
- low
2. `drush cim`
3. create a news and people content
4. verify you can use the "List", "Teaser", and "Image Gallery" paragraph types in the components fields.

D8CORE-3158 Enable more paragraph components on news and people

---

config/sync/config_pages.type.stanford_saml.yml
config/sync/core.entity_form_display.config_pages.stanford_saml.default.yml
config/sync/core.entity_view_display.config_pages.stanford_saml.default.yml
config/sync/field.field.config_pages.stanford_saml.su_simplesaml_affil.yml
config/sync/field.storage.config_pages.su_simplesaml_affil.yml
config/sync/stanford_ssp.settings.yml

- Add configurable option to restrict based on user affiliation.
- 6/3
- medium
1. checkout this branch and the branch in https://github.com/SU-SWS/stanford_ssp/pull/118/files
2. `blt drupal:update`
3. go to `/admin/config/people/simplesaml`
4. choose student affiliation restriction
5. log out
6. try to log back in
7. verify you are denied access.
8. log in with user 1 or re-install your site
9. go back and choose a staff affilitation
10. log out
11. log back in and verify you are granted access.

D8CORE-4339 Allow restriction based on the persons affiliation to the university

---

config/sync/core.entity_view_display.paragraph.stanford_media_caption.default.yml
config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_link.yml

- Make media with caption link title required.
- https://github.com/SU-SWS/jumpstart_ui/pull/101
- https://github.com/SU-SWS/stanford_profile_helper/pull/126
- 6/3
- medium
2. checkout the branch in https://github.com/SU-SWS/jumpstart_ui/pull/101
3. checkout the branch in https://github.com/SU-SWS/stanford_profile_helper/pull/126
4. (optional) sync to amptesting. `drush sql:sync @amptesting.01test @self`
3. `blt drupal:update`
4. `drush cr`
5. Create a basic page and put a "Media with Caption" on it
6. Populate the link field
7. view the page and verify the image is "clickable"
8. verify the screen reader reads the link and the image separately.

D8CORE-4194 Add url text for the link on media w caption paragraph

---

composer.json
config/sync/core.extension.yml
config/sync/editor.editor.stanford_html.yml
config/sync/filter.format.stanford_html.yml
config/sync/mathjax.settings.yml

- MathJax for Latex support in the wysiwyg
- 7/8
- medium
1. `composer require su-sws/stanford_profile:dev-D8CORE-4504`
2. `blt drupal:update`
3. create a basic page
4. in the wysiwyg put a latex formula in like `\[ x^n + y^n = z^n \]`
5. save and verify the page displays a mathematical formula.

D8CORE-4504 Added mathjax for latex formula support

---

config/sync/colorbox.settings.yml
config/sync/field.field.media.stanford_gallery_images.su_gallery_image.yml
tests/codeception/functional/Paragraphs/GalleryCest.php

- Require alt text on gallery images
- Adjust colorbox settings
- 7/8
- low
3. create a basic page with an image gallery
4. ensure you are required to enter an alt text when you upload an image.

D8CORE-4235 Require alt text on gallery images

---

composer.json
tests/codeception/acceptance/Content/BasicPageCest.php
tests/codeception/functional/Paragraphs/GalleryCest.php

- https://github.com/SU-SWS/drupal-patches/pull/4
- Allow users the ability to place a node under an unpublished node in the menu.
- 7/8 would be nice
- low
1. `composer require su-sws/stanford_profile:dev-D8CORE-2594 --no-update`
2. `rm -rf docroot/core; composer update -n`
3. log in and add a contributor or site manager role & remove your administrator role
4. create an unpublished node and place it in the menu
5. create another node and verify you can place it in the menu under the unpublished node.

D8CORE-2594 Allow menu placement under unpublished pages

---

config/sync/field.field.config_pages.stanford_basic_site_settings.su_google_analytics.yml
config/sync/field_validation.rule_set.config_pages_stanford_basic_site_settings.yml
tests/codeception/acceptance/Users/RolesCest.php

- Updated the regex to allow `G-xxxxx` format google account ID.
- 9/15
- medium
3. go to the site settings page `/admin/config/system/basic-site-settings`
4. enter a google account id in the form `G-xxxxxxxx`
5. Verify you can save. (the google code won't be added to the pages because not on prod.)

D8CORE-4668 Allow new google analytics account id format `G-`

---

config/sync/views.view.stanford_publications.yml
tests/codeception/acceptance/Content/PublicationsCest.php

- Added sort to publication lists to sort by month and day after the year.
- 8/12
- medium
1. checkout this branch; drush cim -y
2. create 3 publications using either the newspaper or "other" citation, all with the same name but different dates
3. view /publications and verify they are in the correct date order

D8CORE-4350 Sort publications by month and day along with year

---

composer.json
config/sync/core.extension.yml
config/sync/editoria11y.settings.yml
config/sync/user.role.contributor.yml
config/sync/user.role.site_builder.yml
config/sync/user.role.site_developer.yml
config/sync/user.role.site_editor.yml
config/sync/user.role.site_manager.yml

- Added and configured editoria11y module
- 8/12
- low
1. `composer require su-sws/stanford_profile:dev-D8CORE-4653 --no-update; composer update -n`
3. create any node
4. view the editoria11y icon in the bottom right and view your issues/warnings/errors etc

D8CORE-4653 Add editoria11y module with permissions for contributors

---

config/sync/core.entity_view_display.node.stanford_event.default.yml
config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml
config/sync/core.entity_view_display.node.stanford_event_series.default.yml
config/sync/core.entity_view_display.node.stanford_event_series.search_indexing.yml
config/sync/core.entity_view_display.node.stanford_news.default.yml
config/sync/core.entity_view_display.node.stanford_news.search_indexing.yml
config/sync/core.entity_view_display.node.stanford_page.default.yml
config/sync/core.entity_view_display.node.stanford_page.search_indexing.yml
config/sync/core.entity_view_display.node.stanford_person.default.yml
config/sync/core.entity_view_display.node.stanford_person.search_indexing.yml
config/sync/core.entity_view_display.node.stanford_publication.default.yml
config/sync/core.entity_view_display.node.stanford_publication.search_indexing.yml
config/sync/core.entity_view_mode.node.search_indexing.yml
config/sync/search_api.index.full_site_content.yml

- Added a view mode and configured it for all content types. This will be used for indexing. It'll prevent the unwanted indexing of accessibility parts and sidebar menu
- 9/30
- low
2. `blt drupal:update` or `drush cim -y`
3. `drush sapi-i` to re-index content
4. search for the title of a page like "About"
5. verify you don't see "Main content start" in the search result text.

D8CORE-4759 add specific view mode for search indexing for better control

---

config/sync/views.view.stanford_events.yml

- Change the filters on events list to be more granular
- 9/30
- medium
3. create an event that starts 10 minutes ago and ends 5 minutes ago
4. view `/events` and verify that event does not display.
5. change the event to end 10 minutes in the future
6. view `/events` and verify the event displays.

D8CORE-4693 Filter events by the second instead of the day

---

composer.json
config/sync/core.extension.yml
config/sync/filter.format.stanford_html.yml
config/sync/fontawesome.settings.yml

- Add the fontawesome module so that the icons display in the wysiwyg
- 11/19
- medium
1. `composer require su-sws/stanford_profile:dev-D8CORE-4246`
2. `blt drupal:update` or `blt drupal:install`
3. create a page with a text area
4. fill the text area with some text like `<p class="fab fa-drupal">This is some text</p>`
5. view the ckeditor in normal style and verify the icon displays while editing.

D8CORE-4246 Add fontawesome module for wysiwyg icon support

---

config/sync/block.block.config_pages.yml
config/sync/core.entity_view_display.node.stanford_page.stanford_card.yml
config/sync/core.extension.yml
config/sync/stanford_basic.settings.yml
config/sync/views.view.stanford_basic_pages.yml
tests/codeception/acceptance/Paragraphs/ListsCest.php

- Removed the taxonomy term on list displays
- 11/19
- medium
2. `drush cim -y` or `blt drupal:update` or `blt drupal:install`
3. create a couple basic pages and tag them with some terms
4. create a list page of basic pages
5. verify you don't see the taxonomy term on the list itmes.

D8CORE-4996 Remove taxonomy term on basic page card and list displays

---

config/sync/migrate_plus.migration.stanford_publications.yml

- When importing publications, wrap the body text in a `<p>` tag to format the text correctly. But only do that if the imported content isn't already wrapped in html.
- 11/19
- high
2. `drush cim -y` or `blt drupal:update` or `blt drupal:install`
3. go to `/admin/structure/migrate/manage/default/migrations/stanford_publications/csv-upload` and upload a csv with some body text
4. view the node that was created and verify the body text is wrapped in a `<p>` tag.

D8CORE-4860 Wrap publication importer body text in <p>

---

composer.json
config/sync/migrate_plus.migration.su_stanford_person.yml

- Download stanford-only profile photos using the access_token.
- 11/19
- high
1. checkout this branch.
2. checkout the same branch in https://github.com/SU-SWS/stanford_migrate/pull/42
3. `blt drupal:update`
4. Use public cap credentials. (see me for what those are) and enter those on `/admin/config/importers/person-importer`
5. use my sunet to import on that page with the credentials
6. import the profile `drush mim su_stanford_person`
7. view the created content and verify it uses the default image
8. switch the cap credentials to stanford-only credentials. (see me for what those are)
9. update the content `drush mim su_stanford_person --update`
10. view the content from earlier and verify the image was imported.
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad56 …

D8CORE-4677 Use an access token to fetch stanford-only profile images from CAP

---

config/sync/migrate_plus.migration.stanford_localist_importer.yml

- Forget about events if they are no longer in the feed.
- https://github.com/SU-SWS/stanford_migrate/pull/47
- 1/20
- medium
1. follow the steps in https://github.com/SU-SWS/stanford_migrate/pull/47

D8CORE-5193 Configure localist importer to forget about old events

---

config/sync/core.entity_form_display.config_pages.stanford_events_importer.default.yml
config/sync/field.field.config_pages.stanford_events_importer.su_event_xml_url.yml

- Renamed legacy field and moved it below the localist field
- Thursday
- high
2. config import
3. view `/admin/config/importers/events-importer` and review the changes are applied.

D8CORE-5398 Rename Legacy events importer field

---

config/sync/pathauto.pattern.default.yml
tests/codeception/acceptance/Content/BasicPageCest.php

- Fixed path auto pattern when the parent has a custom url path
- 2/30
- medium
1. You can view the test or...
2. checkout this branch
3. `drush cim -y`
4. create a page and put it in the main menu but configure a custom url path for the page
5. create another page and put it in the menu below the other page, don't configure a custom url
6. after saving, verify the child page has the same custom url path from the parent.

Fix pathauto parent path generation

---

src/Config/ConfigOverrides.php

- ensure `preg_replace` subject is a string for php 8.1
- 
- 

preg_replace of null is deprecated in php 8, use strings

---

config/sync/core.entity_form_display.config_pages.stanford_local_footer.default.yml
config/sync/core.entity_view_display.config_pages.stanford_local_footer.default.yml
config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_pr_co.yml
config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_se_co.yml
config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_tr2_co.yml
config/sync/field.storage.config_pages.su_local_foot_tr2_co.yml

- Added a "third" content block for the local footer.
- 3/5
- medium
1. checkout this branch and the branch from https://github.com/SU-SWS/stanford_profile_helper/pull/175
3. edit the local footer and populate the 4 content blocks
4. view the local footer on all breakpoints
5. see that it looks as you'd expect. (the order of the items changes at different breakpoints. Not much we can do with that)

D8CORE-4974 Added a third content block for the local footer

---

config/sync/core.entity_view_display.node.stanford_person.default.yml
config/sync/views.view.stanford_person.yml

- Remove alt text on images on the people node page and the people lists
- 3/5
- medium
1. Checkout this branch & the branch in https://github.com/SU-SWS/stanford_media/pull/118
2. clear caches and import configs `drush cr; drush cim -y`
3. create a person node with an image. Populate the alt text on the image when uploading
4. view the person node page and verify the image has an empty alt text `alt=""`
5. view the people list page `/people` and verify the same empty alt attribute.

D8CORE-5180 D8CORE-5227 Remove alt text on people images

---

config/sync/core.extension.yml
config/sync/filter.format.stanford_html.yml
config/sync/migrate_plus.migration.stanford_localist_importer.yml

- Localist allows <img> tags but uses `style="height: ##px width: ##px"` instead of using height width attributes. Convert the style to attributes.
- 3/15
- medium
3. import SWS localist events
4. view the test event display and verify the height/width attributes are used.

Process Localist html to fix <img> tag styles to attributes

---

config/sync/views.view.stanford_person_list_terms_first.yml
tests/codeception/acceptance/Content/PersonCest.php

- Display content tagged with nested taxonomy terms over the 2nd level
- 3/16
- medium
2. import configs `drush cim -y`
3. create a people type taxonomy term at at least a 3rd level deep.
4. create a person content and tag it with that term you created
5. view the `/people` page
6. see your piece of content
7. click on the parent most term of the term you created
8. see your piece of content again.

D8CORE-4704 Fix person list to show nested content

---

config/sync/block.block.minimally_branded_subtheme_branding.yml
config/sync/block.block.minimally_branded_subtheme_config_pages.yml
config/sync/block.block.minimally_branded_subtheme_config_pages_stanford_global_msg.yml
config/sync/block.block.minimally_branded_subtheme_config_pages_stanford_super_footer.yml
config/sync/block.block.minimally_branded_subtheme_content.yml
config/sync/block.block.minimally_branded_subtheme_help.yml
config/sync/block.block.minimally_branded_subtheme_local_tasks.yml
config/sync/block.block.minimally_branded_subtheme_main_navigation.yml
config/sync/block.block.minimally_branded_subtheme_messages.yml
config/sync/block.block.minimally_branded_subtheme_pagetitle.yml
config/sync/block.block.minimally_branded_subtheme_search.yml
config/sync/block.block.minimally_branded_subtheme_search_form.yml
config/sync/config_ignore.settings.yml
config/sync/core.extension.yml
tests/codeception/acceptance/SubThemeCest.php

- Enable minimally branded theme so devs don't have to do so via drush
- 3/17
- high
1. checkout the `8.x-2.x` version of the profile
2. do a full site install
3. checkout this branch and the matching branch in https://github.com/SU-SWS/stanford_profile_helper/pull/185
4. do `drush deploy` 2 times
5. verify no errors
6. navigate to `/admin/appearance` and verify the them is available to set as default.

Enable minimally branded theme for easier switching

---

config/sync/core.entity_view_display.node.stanford_event.default.yml
config/sync/core.entity_view_display.node.stanford_event_series.default.yml
config/sync/core.entity_view_display.node.stanford_news.default.yml
config/sync/core.entity_view_display.node.stanford_page.default.yml
config/sync/core.entity_view_display.node.stanford_person.default.yml
config/sync/core.entity_view_display.node.stanford_publication.default.yml

- Restrict a bunch of unnecessary blocks available in layout builder and made them consistent for all content types.
- 3/17
- high
2. config import
3. edit/create a basic page
4. edit the layout builder
5. verify there are fewer and only applicable available blocks available. (no "Powered by Drupal" or other blocks that shouldn't be available.)

Configure layout builder restrictions consistently

---

config/sync/migrate_plus.migration.su_stanford_person.yml

- "Stanford Only" profiles have a different link url. The API returns a flag to identify which ones we need to change
- 4/30
- medium
2. import configs.
3. enter some API credentials for the people importer. (reach out to me for those credentials)
4. import a stanford only profile (reach out to me for that sunetid)
5. view the imported profile
6. verify the link on the profile goes to the profile, not a 404 page.

D8CORE-5629 Adjust profile link url for stanford only profiles

---

config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
config/sync/views.view.stanford_person.yml
config/sync/views.view.taxonomy_term_pages.yml
tests/codeception/acceptance/Content/PersonCest.php

- If a person is tagged with multiple types/groups, we don't want to display types/groups that are not relevant to the current taxonomy term we are viewing.
- This actually also fixes the ticket D8CORE-5657 which needed the headers of the lists adjusted.
- 4/28
- medium
2. import configs
3. configure the taxonomy terms so that there are at least 2 parents with some child tags under those.
4. create a person and tag with multiple child terms from different parents
5. view the parent taxonomy term page
6. verify the child from the other parent isn't displayed.

D8CORE-5729 People term pages: display only child terms groupings

---

modules/stanford_events/stanford_events.install

- Fix update hook. It breaks currently on ACSF deployment because the configuration in the database doesn't match the file config and so it breaks when trying to import configs.
- see https://evolvingweb.ca/blog/resizing-fields-drupal-8-without-losing-data
- asap
- 

Improve event sponsor field update hook

---

composer.json
config/sync/core.entity_form_display.paragraph.stanford_banner.default.yml
config/sync/core.entity_form_display.paragraph.stanford_card.default.yml
config/sync/core.entity_form_display.paragraph.stanford_entity.default.yml
config/sync/core.entity_form_display.paragraph.stanford_gallery.default.yml
config/sync/core.entity_form_display.paragraph.stanford_lists.default.yml
config/sync/core.entity_form_display.paragraph.stanford_media_caption.default.yml
config/sync/core.extension.yml
config/sync/field.field.paragraph.stanford_banner.su_banner_button.yml
config/sync/field.field.paragraph.stanford_card.su_card_link.yml
config/sync/field.field.paragraph.stanford_entity.su_entity_button.yml
config/sync/field.field.paragraph.stanford_gallery.su_gallery_button.yml
config/sync/field.field.paragraph.stanford_lists.su_list_button.yml
config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_link.yml
config/sync/filter.format.stanford_html.yml
config/sync/filter.format.stanford_minimal_html.yml
modules/jumpstart_ui/jumpstart_ui.module
tests/codeception/acceptance/Content/PublicationsCest.php
tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
tests/codeception/functional/Paragraphs/BannerCest.php
tests/codeception/functional/Paragraphs/EntityReferenceCest.php
tests/codeception/functional/Paragraphs/GalleryCest.php
tests/codeception/functional/Paragraphs/WYSIWYGCest.php

- Provide aria-label attribute for paragraph link fields.
- Allow aria-label in the wysiwyg
- 7/30
- medium
1. checkout this branch and the matching branch in [react_paragraphs](https://github.com/SU-SWS/react_paragraphs/pull/114)
2. import configs or install fresh install
3. create a basic page
4. use the various paragraph types and populate the "ARIA Label" field
5. save the page and verify your aria-label is rendered on the link..

D8CORE-4972 Provide aria-label input for links on paragraphs

---

modules/stanford_profile_helper/stanford_profile_helper.module

- Allow users to "Reset to alphabetical" for taxonomy terms. Currently the config_readonly module prevents this action. This change conditionally adds the allowed config only for the given route since that route doesn't actually make any changes to the configuration.
- :shrug: 
- low
- low
1. add `$settings['config_readonly'] = TRUE;` to the bottom of your local.settings.php file
2. Go to edit a taxonomy vocabulary
3. Ensure you are blocked and are unable to submit the form.
4. Go to a taxonomy vocabulary that has at least 2 terms.
5. verify when you click the "Reset to alphabetical" you aren't blocked.

D8CORE-5975 Allow resetting taxonomy term order to alphabetical with the button

---

config/sync/config_pages.type.stanford_basic_site_settings.yml
config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_menu_levels.yml
config/sync/field.storage.config_pages.su_site_menu_levels.yml
modules/stanford_profile_helper/src/Config/ConfigOverrides.php
modules/stanford_profile_helper/tests/src/Unit/Config/ConfigOverridesTest.php
tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php

- Allow site managers the ability to turn on the main menu drop down & choose how many levels to display
- :shrug: 
- low
2. import configs & clear caches
3. Create several levels of menu items. (at least 4 levels)
4. turn on the drop down menu at `/admin/config/system/basic-site-settings`
5. observe the drop down menu shows all levels
6. set the "Maximum Menu Levels" so some value at `/admin/config/system/basic-site-settings`
7. observe the drop down shows only that many levels.

D8CORE-6217 Allow configuring maximum main menu depth

---

composer.json
src/EventSubscriber/EventSubscriber.php

- Fixed the local path for file download. The previous approach wasn't the correct path for the DRUPAL_ROOT somehow.
- :man_shrugging: 
- medium
2. Delete all files in `sites/default/files` directory
3. do a full site install
4. ensure the images were downloaded to your local.

Modify directory permissions when copying the file during install

---

themes/stanford_basic/templates/html.html.twig
themes/stanford_basic/templates/page.html.twig

- [D8CORE-2622](https://stanfordits.atlassian.net/browse/D8CORE-2622): A11y: Put logo (Brand bar) into a landmark
- [D8CORE-4494](https://stanfordits.atlassian.net/browse/D8CORE-4494): A11y: Include skip links in ARIA landmark
- Moving brand bar and skip-links into the header element, so that it is included in the header banner landmark, to fix SiteImprove A11y issue `Text not included in an ARIA landmark`
- When convenient
- Normal
2. Navigate to any page and check that the `Text not included in an ARIA landmark` issue (using the SiteImprove Accessibility Checker) plugin() is gone for the brand bar and skip-links
3. Confirm that there are no visual issues with the rearranging done in this PR
4. Review code.
- …

D8CORE-2622, D8CORE-4494 | @jdwjdwjdw | Move brand bar and skip-links into header landmark banner

---

themes/stanford_basic/templates/page.html.twig

- [D8CORE-6731](https://stanfordits.atlassian.net/browse/D8CORE-6731): DEV | Move help section into header section
- When convenient
- Normal
- Normal
2. Add a global message and confirm that it is displayed below the brand bar within the header
- [D8CORE-6731](https://stanfordits.atlassian.net/browse/D8CORE-6731): DEV | Move help section into header section
[D8CORE-6731]: https://stanfordits.atlassian.net/browse/D8CORE-6731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[D8CORE-6731]: https://stanfordits.atlassian.net/browse/D8CORE-6731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

D8CORE-6731 | @jdwjdwjdw | Move help section to be below brand bar in header
