config/install/core.entity_form_display.user.user.default.yml, config/install/core.entity_view_display.user.user.default.yml, config/install/field.field.user.user.su_display_name.yml, config/install/field.storage.user.su_display_name.yml, config/install/system.performance.yml
- Set cache to 1 year
- with update to stanford_ssp, new user name fields.
- asap
- medium
1. follow steps in https://github.com/SU-SWS/acsf-cardinalsites/pull/17
=> Set cache to 1 year and added saml display name field

config/install/system.site.yml, content/node/4b8018dc-49a6-4018-9c54-e8c3e462beee.json, content/node/6d51339d-ff67-498d-98e9-d8228d36fd51.json, content/paragraph/9df33d0d-239e-4b51-9d97-8703187629b4.json, content/paragraph/bf52b16d-03ef-41dc-b906-4a3a88c2e9ce.json
- Created installed state 404 & 403 pages
- end of sprint 8/30
- low
1. run fresh install `blt drupal:install`
1. as anonymous user view `/admin` and validate theres a message presented
1. still as anonymous user view `/a-page-that-doesnt-exist` and validate a message is presented.
=> D8CORE-337 Created 403 and 404 pages

composer.json, config/sync/editor.editor.stanford_html.yml, config/sync/filter.format.stanford_html.yml
- Added more buttons to the html editor
- soon
- low
follow steps in https://github.com/SU-SWS/acsf-cardinalsites/pull/22
=> D8CORE-455 Modify WYSIWYG

tests/behat/features/DefaultContent.feature
- Adds tests
- ?
- ?
1. Run tests
2. Review code
=> Add default content tests.

config/sync/editor.editor.stanford_html.yml
see https://github.com/SU-SWS/stanford_basic/pull/85
=> D8CORE-545 Fixed style class name

config/sync/core.entity_form_display.node.stanford_page.default.yml, config/sync/core.entity_form_display.paragraph.stanford_banner.default.yml, config/sync/core.entity_view_display.node.stanford_page.default.yml, config/sync/field.field.node.stanford_page.su_page_banner.yml, config/sync/field.storage.node.su_page_banner.yml, config/sync/layout_library.layout.stanford_basic_page_full.yml
- Added a field above the title for banner image/video
- 10/8
- low
1. create a page
1. add a banner image and save
1. ensure the banner appears above the page title and full width of the page.
=> D8CORE-620 Add banner field above title

composer.json, config/install/image.style.breakpoint_2xl_1x.yml, config/install/image.style.breakpoint_2xl_2x.yml, config/install/image.style.breakpoint_lg_1x.yml, config/install/image.style.breakpoint_lg_2x.yml, config/install/image.style.breakpoint_md_1x.yml, config/install/image.style.breakpoint_md_2x.yml, config/install/image.style.breakpoint_sm_1x.yml, config/install/image.style.breakpoint_sm_2x.yml, config/install/image.style.breakpoint_xl_1x.yml, config/install/image.style.breakpoint_xl_2x.yml, config/install/image.style.card_1x_478x318.yml, config/install/image.style.card_2x_956x636.yml, config/install/image.style.cta_1x_507x338.yml, config/install/image.style.cta_1x_596x397.yml, config/install/image.style.cta_2x_1014x676.yml, config/install/image.style.cta_2x_1192x794.yml, config/install/image.style.stanford_circle.yml, config/install/responsive_image.styles.card_478x318.yml, config/install/responsive_image.styles.cta_596x397.yml, config/install/responsive_image.styles.stanford_hero_block_wide.yml
- Creates responsive image styles that match the Decanter breakpoints.
- October 22nd
-  Low
2. Run `composer install`
3. Run `blt drupal:install`
4. Validate that the hero banner image is the correct responsive image style
5. Test on 1x and 2x pixel density screens
6. Run tests
- D8CORE
- D8CORE-334
- https://github.com/SU-SWS/acsf-cardinalsites/pull/29
- https://github.com/SU-SWS/stanford_image_styles/pull/48 
=> D8CORE-334: Responsive image styles

config/sync/editor.editor.stanford_html.yml
See: https://github.com/SU-SWS/stanford_text_editor/pull/8
=> D8CORE-635: Update wysiwyg style options.

config/sync/field.field.node.stanford_page.su_page_components.yml
- Update field label
- 10/23
- low
1. verify on a basic page form, the field label is "Paragraphs"
=> Updated components label to be "Paragraphs"

config/sync/field.field.paragraph.stanford_wysiwyg.su_wysiwyg_text.yml
- As per request from Kerri: "I can build all of the pages, nest them properly, and not worry about having to put content in them until later."
- whenever
- low
1. config import
1. create a basic page
1. verify you can save without entering anything in the wysiwyg
=> Dont require the wysiwyg field

CHANGELOG.md, README.md, composer.json, modules/stanford_paragraph_card/stanford_paragraph_card.info.yml, modules/stanford_profile_config_overrides/stanford_profile_config_overrides.info.yml, modules/stanford_profile_install/stanford_profile_install.info.yml, modules/stanford_profile_styles/stanford_profile_styles.info.yml, stanford_profile.info.yml
=> changed versions for 8.1.0 release

config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.extension.yml, config/sync/views.view.block_content.yml, config/sync/views.view.content.yml, config/sync/views.view.media_library.yml, config/sync/views.view.redirect.yml, config/sync/views.view.taxonomy_term.yml, tests/behat/features/Paragraphs/WYSIWYG.feature
- Exported new config after db updates
- see https://github.com/SU-SWS/acsf-cardinalsites/pull/42
- Asap
- high
1. in the stack `composer require su-sws/stanford_profile:dev-D8.8.0-beta-1`
1. Run a site install
1. confirm the site still functions
=> Updated config after 8.8.0-beta1 dropped

config/sync/editor.editor.stanford_html.yml, config/sync/field.field.paragraph.stanford_banner.su_banner_button.yml, config/sync/field.field.paragraph.stanford_banner.su_banner_header.yml, config/sync/field.field.paragraph.stanford_card.su_card_header.yml, config/sync/field.field.paragraph.stanford_card.su_card_link.yml, config/sync/filter.format.stanford_html.yml, config/sync/paragraphs.paragraphs_type.stanford_wysiwyg.yml, stanford_profile.profile
- Changed some help texts a label
- Change a button text for the top banner field
- eventually
- low
1. do an install or `drush cim`
1. verify the commits are displayed.
=> Buncha changes

composer.json, config/sync/core.extension.yml, stanford_profile.info.yml, stanford_profile.profile
see https://github.com/SU-SWS/stanford_basic/pull/106
=> D8CORE-856 paragraphs edit module for contextual links

config/sync/core.entity_view_display.paragraph.stanford_card.default.yml, config/sync/image.style.card_1192x596.yml, config/sync/image.style.card_1900x950.yml, config/sync/image.style.card_478x239.yml, config/sync/image.style.card_956x478.yml, config/sync/responsive_image.styles.card_2_1.yml
- Change the image styles on the card to be a 2:1 ratio
- 12/11
- low
1. drush cim & drush cr
1. create or view a card paragraph type
1. validate the image appears in a 2:1 ratio.
=> D8CORE-854 Make card paragraph image 2:1 ratio

CHANGELOG.md, README.md, modules/stanford_paragraph_card/stanford_paragraph_card.info.yml, modules/stanford_profile_install/stanford_profile_install.info.yml, modules/stanford_profile_styles/stanford_profile_styles.info.yml, stanford_profile.info.yml
https://github.com/SU-SWS/stanford_profile/compare/8.1.0-alpha.2...tag-8.1.0-alpha3
Needed for https://github.com/SU-SWS/acsf-cardinalsites/pull/48
I'm not sure of the wording of everything in the CHANGELOG.
This can wait until after Winter Closure.
=> 8.1.0-alpha3

config/sync/core.entity_form_display.media.image.media_library.yml, config/sync/core.entity_view_display.paragraph.stanford_card.default.yml
See https://github.com/SU-SWS/acsf-cardinalsites/pull/49
=> changed the widget for the media library form mode on images

CHANGELOG.md, modules/stanford_paragraph_card/stanford_paragraph_card.info.yml, modules/stanford_profile_install/stanford_profile_install.info.yml, modules/stanford_profile_styles/stanford_profile_styles.info.yml, stanford_profile.info.yml
- D8CORE-970: adding wysiwyg scss file (#60)
- D8CORE-850 Added Ckeditor Sticky Toolbar (#51)
- Changed the widget for the media library form mode on images (#56)
- Adjusted some wysiwyg styles.
- Improvements to the admin UI
- Deploy and run both database updates and config import
- normal risks with core and module updates.
- https://github.com/SU-SWS/stanford_profile/compare/8.1.0-alpha.3...8.1.0-alpha.4
=> 8.1.0-alpha.4

CHANGELOG.md, modules/stanford_paragraph_card/stanford_paragraph_card.info.yml, modules/stanford_profile_install/stanford_profile_install.info.yml, modules/stanford_profile_styles/stanford_profile_styles.info.yml, stanford_profile.info.yml
```
- D8CORE-1200: Prevent home page from being deleted (#68)
- D8CORE-1013: Allow classes on header elements (#67)
- Fix for focal point config mis-match and failed circle ci behat tests.
- Improvements to the admin UI
- Deploy and run both database updates and config import
- normal risks with core and module updates.
- https://github.com/SU-SWS/stanford_profile/compare/8.1.0-alpha.4...8.1.0-alpha.5
```
=> 8.1.0-alpha.5

.circleci/config.yml, src/Plugin/HelpSection/ProfileConnectSection.php, src/Plugin/HelpSection/ProfileHelpSection.php, src/Plugin/HelpSection/ProfileHelpTrait.php, src/Plugin/HelpSection/ProfileResourceSection.php, stanford_profile.profile, tests/src/Kernel/Plugin/InstallTask/SiteSettingsTest.php, tests/src/Unit/Plugin/HelpSection/ProfileConnectSectionTest.php, tests/src/Unit/Plugin/HelpSection/ProfileHelpSectionTest.php, tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
- Added help sections for product support
- Styling/templating is needed to get the best result. Which would require a subtheme. Thats out of scope for this ticket.
- RC1
- low
1. clear all caches
1. view `/admin/help`
1. verify the help text is there.
=> D8CORE-1175 Provide additional help information

stanford_profile.profile
- Changed "Content" -> "All Content" in admin menu
- Changed "Media" -> "All Media" in admin menu
- 2/12
- low
1. checkout this branch and clear cached
1. validate the admin menu items are changed.
=> D8CORE-1018 Adjust content and media menu item titles

composer.json
What it says on the tin. 
- Validate hash and merge
=> Lock su-sws/react_paragraphs to hash

config/sync/block.block.stanford_basic_pagetitle.yml
- Added page title for non-node pages
- end of the week.
- medium
1. Check this branch and `drush cim`
1. search for some text via the header search field
1. on the search result page, validate the page title is displayed as an `<h1>`
=> Added page title for non-node pages

composer.json, config/sync/core.extension.yml
- What the title sayz
- :man_shrugging: 
- low
1. validate the module is added.
=> Added field_formatter_class module

config/sync/layout_library.layout.stanford_basic_page_full.yml
- Ready for review
- Make sure titles never bump up on the left chrome rail
- 2/14 if possible
- medium
1. Pull in this profile
2. Add content page with a full width layout.
3. Verify the title doesn't bump the far left side.
- Version 1.0 of our project
- D8CORE-1019
- @kerri-augenstein , We didn't need a class but could do in the layout/profile.
=> D8CORE-1019 Modified the full width layout

README.md, modules/stanford_paragraph_card/stanford_paragraph_card.info.yml, modules/stanford_profile_install/stanford_profile_install.info.yml, modules/stanford_profile_styles/stanford_profile_styles.info.yml, stanford_profile.info.yml
=> Imonroe patch 1

config/sync/views.view.media_library.yml
- Resync the view to core view.
- 2/25
- medium
1. checkout this branch.
1. import config.
1. navigate to `/admin/content/media`
1. validate the "table" and "grid" links at the top work.
=> Resync the media library view with the drupal core version

config/sync/core.extension.yml, config/sync/editor.editor.stanford_html.yml, config/sync/filter.format.stanford_html.yml, config/sync/filter.format.stanford_minimal_html.yml, config/sync/user.role.contributor.yml, config/sync/user.role.site_builder.yml, config/sync/user.role.site_developer.yml, config/sync/user.role.site_editor.yml, config/sync/user.role.site_manager.yml, content/node/72f0069b-f1ec-4122-af73-6aa841faea90.json, content/paragraph/35b55d09-f3e6-4134-87c1-4a8ea132940f.json, content/paragraph/79c98714-281a-450d-b574-2971426b1f3e.json, content/paragraph/9954cc81-919b-4498-9151-bf930831fca7.json, content/paragraph/b7abb133-a21b-4a1a-a13c-f630aad2ce7e.json, content/paragraph/cffc69b9-51a3-4e0e-a1b3-864202e42e6c.json, content/paragraph/fbbaaecc-80fc-494a-8bce-83638d1d668d.json, stanford_profile.info.yml, stanford_profile.profile
- Removed contextual links permission for all but developer role
- Changed the text style "Related Text" to "Card Text"
- Updated default content for the home page to put the banner in the "Top Banner" filed
- Allow `<br>` tags in the wysiwyg
- Added a help text for the layout selection field
- Enabled view_unpublished module and allowed site managers and higher to view unpublished content.
- 2/28
- medium
1. validate the above
=> D8CORE-1363 D8CORE-1262 D8CORE-1365D8CORE-1394 D8CORE-1224  D8CORE-1326

composer.json
- Set paragraphs to a version
- next week would be great
- low
=> Fixed drupal/paragraphs version

config/sync/ds.field.su_site_name.yml, config/sync/editor.editor.stanford_html.yml, config/sync/filter.format.stanford_html.yml
- Enables stanford_media's filter for the full html text format
- Thursday
- Medium
1. Review code
2. Wait for tests
3. Do a fresh install with stanford_media and stanford_text_formats on `8.x-1.x`
4. Manually review filter is enabled and working by visiting admin page and reviewing markup of default view mode image in wysiwyg.
=> D8CORE-1409: Enable new filter in the full html format.

src/Plugin/InstallTask/SiteSettings.php
- Disable nobots via state on site install
- tomorrow
- high
1. do a fresh install
1. validate the nobots response header is not set on any page load
=> Disable nobots via state on site install

config/sync/field.field.config_pages.stanford_saml.su_simplesaml_roles.yml, config/sync/simplesamlphp_auth.settings.yml
- Changed workgroups to limit who has access
- next release
- medium
1. do a fresh install
1. log into your local site
1. verify you still have admin.
=> Changed default workgroup for saml role mapping

content/media/08f26cab-7525-47c3-89ed-1d77094a3ead.json, content/media/0c33d58c-1a4a-49fa-a590-42e4ef8fc651.json, content/media/13eb6419-1379-4180-8ce0-69d2fcf39ef3.json, content/media/33324210-4657-4685-8ff3-834160b32a14.json, content/media/381f792e-24b4-4c50-b5cc-69c13702f93a.json, content/media/39cadd28-7a7e-4648-868d-d5e4f0a69bf7.json, content/media/3b196c11-47c7-40a2-acbd-d48369e31669.json, content/media/5d11d1f1-9844-424c-b5ea-523e7d1ada38.json, content/media/5e2a5f6b-fa5f-42c1-a189-a2c16ec406b5.json, content/media/66286339-4f00-4994-8c0d-921b519ea4e4.json, content/media/6fac3713-f499-4750-a7bc-32c16a59043a.json, content/media/81a60c63-7638-46d2-8fd9-b4de2cbc3554.json, content/media/847af305-af5e-4cea-9175-8f40127a408c.json, content/media/ad1e4d74-148a-43d7-a054-091dcd23ab33.json, content/media/da0afb6c-f753-4d8b-9aec-720e47983de3.json
- Added alt text to the default content media images.
- https://github.com/SU-SWS/acsf-cardinalsites/pull/99
- 3/12
- low
1. do a fresh install
1. validate the media items have alt text for each image.
=> D8CORE-1405 Added alt text to default content

config/sync/user.role.site_builder.yml, config/sync/user.role.site_editor.yml, config/sync/user.role.site_manager.yml, tests/behat/features/Users/Roles.feature
- Added administer media permission for site manager and higher
- 3/19
- medium
1. drush cim -y
1. log in as a site manager
1. verify you have access to the media list at `/admin/content/media`
=> D8CORE-1514 Add administer media permission to site managers

tests/behat/features/Paragraphs/WYSIWYG.feature
- see https://github.com/SU-SWS/stanford-caravan/pull/8
- Use the step definition
- asap
- medium
=> Added step in behat tests to wait for modal to be gone

tests/behat/features/Paragraphs/WYSIWYG.feature
- Make edit link clicking more specific
- very soon
- medium
1. review tests.
=> Make edit link clicking more specific

.circleci/config.yml, composer.json, tests/codeception/acceptance/DemoCest.php, tests/codeception/acceptance/HomePageCest.php
- Set up codeception tests
- some later date
- low
1. review tests
=> Set up codeception tests framework

config/sync/dropzonejs.settings.yml
- Automated pull request created via BLT
- As soon as possible
- This is a maintenance pull request
- This PR contains automated updates to keep the stack up to date.
- Attention: @jbickar @sherakama @pookmish @imonroe @boznik
The following changes since commit 2d6b91bbe2f47ad8043cffd0a43f31c84925ba27:
8.1.5 (#156) (2020-03-20 14:42:57 -0700)
are available in the git repository at:
./
for you to fetch changes up to 2d6b91bbe2f47ad8043cffd0a43f31c84925ba27:
8.1.5 (#156) (2020-03-20 14:42:57 -0700)
----------------------------------------------------------------
=> dependency_update_1586088263

composer.json, tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
Test for https://github.com/SU-SWS/react_paragraphs/pull/41
=> D8CORE-1943 Tests for Fix links in the react widget

tests/behat/features/BasicPage.feature
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> Fixed revision tab link test now that the name has changed

config/sync/field.field.paragraph.stanford_banner.su_banner_sup_header.yml, config/sync/field.field.paragraph.stanford_card.su_card_super_header.yml, tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
- Changed a couple field labels to make them similar.
- 5/14
- low
1. see that the labels are changed on the banner and card paragraphs
- JIRA ticket
- Other PRs
=> D8CORE-1870 Change field labels on the card and banner paragraphs

config/sync/field.field.node.stanford_page.su_page_components.yml
- Sets cards to 3-in-a-row
- Sooon
- high
1. What else needs to change? Anything?
- D8CORE
=> D8CORE-000: Set cards to 3 in a row.

config/sync/ultimate_cron.job.node_revision_delete_cron.yml
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> Changed cron job to every minute

.github/auto-label.json, .github/workflows/label.yml, content/node/4b8018dc-49a6-4018-9c54-e8c3e462beee.json, content/node/6d51339d-ff67-498d-98e9-d8228d36fd51.json, content/node/72f0069b-f1ec-4122-af73-6aa841faea90.json, content/node/bc484600-a21a-4497-b9f7-f928474b511c.json, content/node/d21d84f0-22e7-4596-82cb-9209841a3276.json, content/node/e18a741f-7d86-492a-a02f-7ca73989ca13.json
- Update to target IDs in default content and move over the auto tagger.
=> misc fixes.

config/sync/migrate_plus.migration.stanford_events_importer.yml
- Use a process plugin to correctly set the timezone.
- tomorrow.
- high.
=> Use process plugin for the timezone field

config/sync/views.view.stanford_events.yml, config/sync/views.view.stanford_events_past.yml
- Removes labels from events views
- ASAP
- Today
1. Review code changes
2. Trust me
3. Merge
These changes went into the module here: https://github.com/SU-SWS/stanford_events/pull/5
=> D8CORE-000: Events feedback.

stanford_profile.post_update.php
=> Added notifications about events and person importer

config/sync/core.entity_view_display.node.stanford_person.default.yml
- Change "Telephone" to "Contact"
- Friday
- low
1. pull in the config changes.
2. verify the right column on the person node says Contact instead of Telephone
- stanford_person module
- D8CORE-2049
https://github.com/SU-SWS/stanford_person/pull/97
https://github.com/SU-SWS/stanford_profile/pull/241
- @cjwest 
=> D8CORE-2049: change telephone to contact

config/sync/field.field.node.stanford_person.su_person_first_name.yml, config/sync/field.field.node.stanford_person.su_person_full_title.yml, config/sync/field.field.node.stanford_person.su_person_last_name.yml, config/sync/field.field.node.stanford_person.su_person_photo.yml, config/sync/field.field.node.stanford_person.su_person_short_title.yml, config/sync/field.storage.node.su_person_first_name.yml, config/sync/field.storage.node.su_person_full_title.yml, config/sync/field.storage.node.su_person_last_name.yml, config/sync/field.storage.node.su_person_photo.yml
See: https://github.com/SU-SWS/stanford_person/pull/94
=> D8CORE-2099: Added required fields and default image for profile.

config/sync/core.entity_view_display.node.stanford_event.default.yml
- Move the CTA into the details box.
- Soonish
- Medium
- Core product, Events accelerant
2. Navigate to an Events node. Likely have to create one. Make sure to add the CTA button.
3. Verify there is a CTA button inside the details box.
- D8CORE-2290
- https://github.com/SU-SWS/stanford_profile/pull/247
https://github.com/SU-SWS/stanford_events/pull/15
=> D8CORE-2290: moved the cta into details area

composer.json
- Lock view unpublished to avoid the error in issue [#3097251](https://www.drupal.org/project/view_unpublished/issues/3097251#comment-13729547)
- asap
- high
1. verify the tests pass
=> Lock view unpublished to avoid the error in issue #3097251

config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_url.yml
LMK if this is the wrong way to go about this.
=> Update help text for Site URL

config/sync/views.view.stanford_person_terms.yml
- A11y fix for a span wrapping a div.
- Thursday
- Med
- Core, person module
2. Navigate to a filtered person page. You might need to add Haley our sample to a taxonomy term.
3. Verify the top description of "Faculty ... text" is not wrapped in a span tag. 
- Person Module
- Accessibility
- D8CORE-2007
- https://github.com/SU-SWS/stanford_profile/pull/249
- https://github.com/SU-SWS/stanford_person/pull/98
- A11y fix
- @cjwest 
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack …
=> D8CORE-2007: removing the span as a wrapper

composer.json, config/sync/config_pages.type.stanford_local_footer.yml, config/sync/views.view.media.yml, tests/codeception/acceptance/LocalFooterCest.php, tests/codeception/acceptance/Users/RolesCest.php
- see https://github.com/SU-SWS/stanford_profile_helper/pull/2
- Resolved menu items not visible for certain roles.
- 7/8
- medium
1. review tests for menu link checking.
=> D8CORE-2282 D8CORE-2293 Tests for admin toolbar links

src/Plugin/HelpSection/ProfileHelpSection.php, src/Plugin/HelpSection/ProfileResourceSection.php, tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
- Update help sections
- :shrug: low priority.
- low
1. clear caches
1. view the `/admin/help` to see the changes.
=> D8CORE-2229 Update help section texts

config/sync/views.view.stanford_event_series.yml, config/sync/views.view.stanford_events.yml
- syncing up the Event changes
- 7/10
- High
1.pull in this branch.
2. make sure events looks as expected.
- Events
- D8CORE-2317
=> D8CORE-2317: location changes to events

composer.json
=> DEVOPS-000: Remove field formatter patch

config/sync/filter.format.stanford_html.yml
- Updated html filter to allow colspan and rowspan.
- asap
- low
1. Pull this branch
2. Clear cache
3. Create a table
Sample table:
```
<table>
<thead>
<tr>
<th class="text-align-center" scope="col">ABC</th>
<th class="text-align-center" scope="col">XYZ</th>
<th class="text-align-center" scope="col">123</th>
</tr>
</thead>
<tbody>
<tr>
<td class="text-align-center">Duis arcu tortor</td>
<td class="text-align-center">suscipit eget</td>
<td class="text-align-center">imperdiet nec</td>
</tr>
<tr>
<td class="text-align-center" colspan="3">I am a full width row.&nbsp;Vestibulum volutpat pretium libero.</td>
<td class="text-align-center"></td>
<td class="text-align-center"></td>
</tr>
<tr>
<td class="text-align-center">imperdiet iaculis</td>
<td class="text-align-center">lorem ipsum.</td>
<td …
```
=> D8CORE-2478 Updated html filter to allow colspan and rowspan.

composer.json
- Updates patch
- Soonish as builds are breaking.
- Medium
1. Review code changes
2. Review passing tests
3. For bonus points do a full cardinalsites build with this branch.
=> DEVOPS-000: Update paragraphs lang patch

config/sync/core.entity_form_display.node.stanford_page.default.yml
- Added settings to limit how many items can be in a row by setting the required columns.
- asap
- high
1. checkout this branch and the same branch in https://github.com/SU-SWS/react_paragraphs/pull/61
1. run config import
1. attempt to add 2 banners to the same row
1. validate you can't do that.
=> react columns

stanford_profile.post_update.php
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> HOTFIX-000: Fix up unpublished content

stanford_profile.post_update.php
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> added condition to only get untouched nodes

tests/codeception/functional/Users/RolesCest.php
- I built out this test, so we might as well use it. It verifies the user can't bulk delete the home page.
- 10/5 i guess
- low
1. View the tests.
=> D8CORE-1200 Additional permission check for deleting home page

composer.json, tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
see https://github.com/SU-SWS/jumpstart_ui/pull/76
=> D8CORE 2498 local footer

config/sync/views.view.stanford_news.yml
- change the pagination numbers
- Monday
- High
2. Update the profile configs.
3. Generate news articles with high numbers.
4. Click on the load more and verify there are no more repeated titles. 
- Basic, News, SOE
- D8CORE-2548
https://github.com/SU-SWS/stanford_news/pull/100
=> D8CORE-2548: change the pagination counts

composer.json, tests/codeception/acceptance/Media/MediaFormsCest.php
- Acceptance tests to go with https://github.com/SU-SWS/stanford_profile_helper/pull/27
- These tests won't pass until that PR is merged.
- next code cutoff.
- 3 out of 10.
1. Let the tests run, make sure there's no failures.
- https://github.com/SU-SWS/stanford_profile_helper/pull/27
=> D8CORE-2644: Tests for embeddable media form alters

composer.json, tests/codeception/acceptance/Content/PersonCest.php, tests/codeception/acceptance/LocalFooter/LocalFooterCest.php, tests/codeception/functional/Users/RolesCest.php
- tests for https://github.com/SU-SWS/stanford_profile_helper/pull/28
=> D8CORE-2613: Tests for manipulating taxonomy terms and the menu

composer.json, config/sync/core.entity_view_display.node.stanford_person.default.yml, config/sync/core.extension.yml, config/sync/react_paragraphs.paragraphs_row_type.node_stanford_page_row.yml
- Enable the react_paragraphs_behaviors module
- after https://github.com/SU-SWS/react_paragraphs/pull/70 is merged
- low
=> D8CORE-2685 Enable react behaviors module

composer.json, tests/codeception/acceptance/Paragraphs/ListsCest.php, tests/codeception/functional/Paragraphs/EntityReferenceCest.php
- https://github.com/SU-SWS/stanford_profile_helper/pull/35
=> D8CORE-2875 Allow all paragraph types in tests

composer.json
- Added patch for token module.
- soon
- high.
=> Patch token module

src/Plugin/HelpSection/ProfileHelpSection.php
- Updated feedback form link url
- ASAP
- high
1. checkout the branch
1. view the help page
1. verify the link is updated.
=> D8CORE-2957 Updated feedback form link url

src/Plugin/HelpSection/ProfileHelpSection.php
- Updated help section language
- 12/3
- low
1. view `/admin/help`
1. validate the language change is visible.
=> D8CORE-2957 Updated help section language

composer.json
Patch was re-rolled today.
- Replaces patch with new version
- ??
- Patch is necessary for installation.
=> Updated patch for config_ignore

composer.json, tests/codeception/functional/Navigation/NavigationDropDownsCest.php
- tests to go along with https://github.com/SU-SWS/stanford_basic/pull/206
- end of sprint
- needed for dropdown menu feature in 2.0
1. Observe that tests pass.
=> D8CORE-1123: added tests for dropdown menu

config/sync/core.entity_view_display.node.stanford_event.default.yml, config/sync/views.view.stanford_events.yml
- profile copy of the changes in https://github.com/SU-SWS/stanford_events/pull/50
- Fixes problem with deleted schedule events showing up.
- Today
- 
1. Checkout branch
2. drush cim
2. create an event
3. add schedule to event
4. make sure schedule shows up
5. delete schedule
6. make sure deleted schedule doesn't show up.
=> D8CORE-2968 Change the events schedule view

composer.json, config/sync/core.extension.yml, stanford_profile.info.yml
- Moved patches to the shared patches package.
- Use stable 9 theme and the latest stanford_basic theme.
- :shrug: 
- low
1. `composer require su-sws/stanford_profile:dev-drupal-patches`
3. view the site and ensure you don't get any errors
=> Moved patches to shared package and use Stable 9 theme.

composer.json, config/sync/core.entity_form_display.citation.su_other.default.yml, config/sync/core.entity_view_display.citation.su_other.default.yml, config/sync/field.field.citation.su_other.su_author.yml, config/sync/field.field.citation.su_other.su_day.yml, config/sync/field.field.citation.su_other.su_month.yml, config/sync/field.field.citation.su_other.su_publisher.yml, config/sync/field.field.citation.su_other.su_subtitle.yml, config/sync/field.field.citation.su_other.su_url.yml, config/sync/field.field.citation.su_other.su_year.yml, config/sync/field.field.node.stanford_publication.su_publication_citation.yml, config/sync/stanford_publication.citation_type.su_other.yml, config/sync/views.view.stanford_publications.yml, tests/codeception/acceptance/Content/PublicationsCest.php
- Added an "Other" citation type.
- https://github.com/SU-SWS/stanford_publication/pull/35
- 4/8
- medium
1. checkout this branch and the same branch name from https://github.com/SU-SWS/stanford_publication/pull/35
2. `drush cim`
3. create a publication
4. choose "Other" from the citation information and enter some data.
5. save and verify it looks like any regular publication node.
=> D8CORE-3538 Add "Other" citation type

composer.json, tests/codeception/acceptance/HomePageCest.php
- Acceptance tests for https://github.com/SU-SWS/stanford_profile_helper/pull/93
- 4/7
- medium
1. nothing to test here. see steps in https://github.com/SU-SWS/stanford_profile_helper/pull/93
=> D8CORE-2853 test for unpublishing the home page

config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
- Removing the extra h2. Correction to a previous pull. 
- 3/4
- Med
1. Pull in the config change.
2. Clear caches.
3. Add teasers on a page.
4. Verify it looks as design noted: 
https://stanfordits.atlassian.net/browse/D8CORE-4020
- Teasers for publications
- D8CORE-4020
- https://github.com/SU-SWS/stanford_profile/pull/393
- https://github.com/SU-SOE/soe_basic/pull/71
- https://github.com/SU-SWS/stanford_profile_helper/pull/96
=> D8CORE-4020: fixup on config

config/sync/config_pages.type.stanford_saml.yml, config/sync/stanford_ssp.settings.yml
- Replace "Whitelist" with "Allowed"
- asap
- high
1. see https://github.com/SU-SWS/stanford_ssp/pull/108
=> D8CORE-3953 Replace "whitelist" with "allowed" for stanford_ssp

composer.json, config/sync/field.field.config_pages.stanford_global_message.su_global_msg_message.yml
- Config changes for global message config form.
- soon.
- 2 of 10
- 
2. run a `composer update`
3. run a `drush cim`
4. Try to enable a global message without filling out at least one of the fields in the form.
- JIRA ticket
- Other PRs
=> D8CORE-2766: config change for global message form

config/sync/core.entity_form_display.node.stanford_event.default.yml, config/sync/core.entity_form_display.paragraph.stanford_schedule.default.yml, config/sync/field.field.node.stanford_event.su_event_alt_loc.yml, config/sync/field.field.node.stanford_news.su_news_topics.yml, config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml, config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
- adjusted help text and form displays
- 5/5
- low
1. probably just looking at the configs is enough unless you want to check the help text on the individual fields.
=> D8CORE-3104 D8CORE-3455 D8CORE-3456 D8CORE-3981 Help text and form tweaks

config/sync/views.view.user_search.yml
- Added a new form for searching users of a site based on name, role, or whether the account is active or not.
- 5/6/21
- medium
2. `drush cim` 
3. You should now see a new entry under the `People` menu for `User Search`.  Use that button, or navigate manually to `/admin/people/user-search`
4. Verify the user search works with various options.
- JIRA ticket
- Other PRs
=> D8CORE-3523: Added User Search form

composer.json, config/sync/core.extension.yml, config/sync/views.view.user_admin_people.yml, tests/codeception/acceptance/AuthenticatedPermissionsCest.php, tests/codeception/acceptance/Users/DefaultUsersCest.php, tests/codeception/acceptance/Users/RolesCest.php
- Change "People" to "Users"
- 5/18
- low
1. see steps in https://github.com/SU-SWS/stanford_profile_helper/pull/110
2. Correct composer.json after the above PR is merged.
=> D8CORE-2028 Change "People" to "Users" in the admin toolbar

config/sync/colorbox.settings.yml
- Change colorbox settings
- 5/18
- medium
1. see steps in https://github.com/SU-SWS/stanford_profile_helper/pull/113
=> D8CORE-4104 Adjust colorbox settings

composer.json, config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml, config/sync/core.entity_view_display.node.stanford_event.teaser.yml, config/sync/core.entity_view_display.paragraph.stanford_person_cta.default.yml, config/sync/core.entity_view_display.paragraph.stanford_schedule.default.yml, config/sync/views.view.stanford_event_series.yml, config/sync/views.view.stanford_events.yml, config/sync/views.view.stanford_events_past.yml
- https://github.com/SU-SWS/stanford_events/pull/70/files
- Updated configs for the refactored patterns
- 5/20
- medium
1. Checkout this branch and the branch in https://github.com/SU-SWS/stanford_events/pull/70/files
2a. Use a new site: `drush cr` & `drush cim`
2b. Use an existing site: `drush sql:sync @[sitename].01live @self` & `blt drupal:update`
3. create some events
4. view the `/events` page and verify it still looks the same. 
5. view an event node page
6. verify the "related" events at the bottom still looks the same.
=> D8CORE-2520 reset configs for events refactored patterns

.circleci/config.yml, tests/codeception/acceptance/Content/NewsCest.php, tests/codeception/acceptance/Users/IntranetCest.php, tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> fixed test to pass

composer.json, config/sync/core.entity_view_display.node.stanford_event.default.yml, config/sync/core.entity_view_display.node.stanford_event_series.default.yml, config/sync/core.entity_view_display.node.stanford_news.default.yml, config/sync/core.entity_view_display.node.stanford_page.default.yml, config/sync/core.entity_view_display.node.stanford_person.default.yml, config/sync/core.entity_view_display.node.stanford_publication.default.yml, config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml, config/sync/google_tag.settings.yml, config/sync/system.advisories.yml, config/sync/system.rss.yml, config/sync/views.settings.yml
- I updated drupal core and everything, ran database updates, and exported the configs.
- July?
- low
=> Exported configs after Drupal 9.2.0 upgrade

config/sync/page_manager.page_variant.event_series-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_events_list-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_events_past-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
- Added the skip to main content on list pages that was missing
- June 26
- Med
- Accessibility
- Events
- Event Series
- Past Events
- People
- medium
1. Check out this branch and the related pull request
3. Make sure you have news, people, event series, past events and events 
4. Verify you can use the skip to links for both the secondary navigation and the main content well.  
5. This change is big and must be reviewed by @cjwest 
- [D8CORE-4378](https://stanfordits.atlassian.net/browse/D8CORE-4378)
- https://github.com/SU-SWS/stanford_news/pull/127
- …
=> D8CORE-4378: adding the skip to main content on these list pages

config/sync/field.field.node.stanford_event_series.su_event_series_components.yml, config/sync/field.field.node.stanford_event_series.su_event_series_event.yml, config/sync/field.field.node.stanford_event_series.su_event_series_subheadline.yml, config/sync/field.field.node.stanford_event_series.su_event_series_type.yml
- This PR tweaks some help text for the Event Series content type
- code freeze
- low
- low
3. Create an Event Series content item.  
4. Make sure the help text makes sense.  Further discussion: https://stanfordits.atlassian.net/browse/D8CORE-2278
- Other PRs
- [Accessibility Manual Test …
=> D8CORE-2278: Tweaks to Event Series help text

config/sync/field.field.node.stanford_event.su_event_components.yml, config/sync/field.field.node.stanford_event.su_event_email.yml, config/sync/field.field.node.stanford_event.su_event_map_link.yml, config/sync/field.field.node.stanford_event.su_event_schedule.yml, config/sync/field.field.node.stanford_event.su_event_telephone.yml, config/sync/field.field.paragraph.stanford_person_cta.su_person_cta_link.yml, config/sync/field.field.paragraph.stanford_person_cta.su_person_cta_name.yml, config/sync/field.field.paragraph.stanford_person_cta.su_person_cta_title.yml, tests/codeception/acceptance/Content/EventsCest.php
- This PR tweaks some of the help text for the Event content type and the Person CTA.
- next code freeze
- low
- low
3. Create an Event and make sure the help text is correct and makes sense.  See also https://stanfordits.atlassian.net/browse/D8CORE-2277 for further discussion.
- Other PRs
- …
=> D8CORE-2277: updated help text

config/sync/page_manager.page_variant.people-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_events_list-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml, config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
=> D8CORE-4643 Swapped out the "menu block" block with a regular "menu" block

config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
- Adding a skip to main anchor
- 7/16/21
- Med
- Affects all the subthemes
- It is for the keyboard users
- Medium
- a11y task
3. Create some publications and taxonomy terms.
4. Navigate to  /publications/filter name
5. Verify you can use the tab skip links to the main content and to the secondary navigation
- Publications module
- Themes and subthemes
- Skip links
- D8CORE-4525 (related)
- D8CORE-4534
- https://github.com/SU-SWS/stanford_profile/pull/437
- https://github.com/SU-SWS/stanford_basic/pull/235
- @cjwest 
- …
=> D8CORE-4534: adding a skip anchor block to the filtered pub page

composer.json, config/sync/core.extension.yml, config/sync/stanford_actions.settings.yml, config/sync/views.view.content.yml, tests/codeception/acceptance/Content/BasicPageCest.php, tests/codeception/acceptance/Content/EventsCest.php, tests/codeception/acceptance/Content/NewsCest.php, tests/codeception/acceptance/Content/PersonCest.php
- Configured stanford_actions
- 9/30
- high
1. `composer require su-sws/stanford_profile:dev-D8CORE-3026 --no-update; composer update -n`
2. `blt drupal:update` or `blt drupal:install`
3. create or clone existing content from `/admin/content` page
=> D8CORE-3026 added and configured stanford_actions

src/Plugin/HelpSection/ProfileConnectSection.php, src/Plugin/HelpSection/ProfileHelpSection.php, src/Plugin/HelpSection/ProfileResourceSection.php, tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
- Updated help page texts.
- 9/30
- low
1. checkout this page
2. clear caches
3. view `/admin/help` and verify the text changes.
=> D8CORE-4096 Updated help section text

config/sync/filter.format.stanford_html.yml
- Adding the class to the table element.
- Adding the `aside` element. This part was requested by @cjwest for her ticket. 
- For the ability to use pull-content within the WYSIWYG. See PR https://github.com/SU-SWS/decanter/pull/807 
- 10/27
- Normal
- Needed for VPUE Subtheme and @cjwest's ticket
- Normal
3. Navigate to a Basic Page. Add a table in source view with `class`.
4. Verify the class isn't stripped.
5. Add an `aside` with a `class` and verify it isn't stripped out.
- Is there a config:export in this PR that changes the config sync directory? It is one.  :) 
- Core 
- Stanford Basic theme
- All subthemes
- [D8CORE-4871](https://stanfordits.atlassian.net/browse/D8CORE-4871)
- @cjwest's: See Decanter …
=> D8CORE-4871: adding a class to the table element and the aside element

config/sync/field.field.config_pages.stanford_events_importer.su_localist_url.yml
- Added help text to the localist importer field.
- next code freeze.
- 2
- Normal
3. Navigate to the events importer.
4. Verify the help text appears below the Localist importer field.
- Other PRs
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAk …
=> D8CORE-5119: added help text for the localist import field.

config/sync/extlink.settings.yml
- Have the external links module skip the localist embed
- Removed the visibility-none solution since it is now excluded from the external links config.
- soonish
- Effects the use of localist
- Normal
3. There's plenty of content on amptesting so clone that down and look at this link locally.
4. /interior-page/test-wysiwyg/headings-font-weight - the headings should have the external link icons. 
5. /events/localist-embeddable - the whole card should be clickable. There should be no external link arrow icons. 
- This needs to happen for the Localist release Feb 1
- D8CORE-5183
- …
=> D8CORE-5183: changes to config to skip localist

config/sync/block.block.stanford_basic_search.yml, config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml, config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml, config/sync/field.field.config_pages.stanford_basic_site_settings.su_hide_site_search.yml, config/sync/field.storage.config_pages.su_hide_site_search.yml, tests/codeception/acceptance/Content/SearchBlockCest.php
- This PR adds a checkbox to allow site owners to optionally disable the site search block at the top of the page.
- Code cutoff
- 3
- Normal
3. Navigate to `/admin/config/system/basic-site-settings`
4. Verify there is a checkbox labeled "Hide Site Search" at the bottom of the form.
5. Check the checkbox, save the page.
6. Navigate to the homepage (or any other page) and verify the site search form at the top of the page is not displayed.
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this …
=> Added checkbox to hide site search in site settings config page

config/sync/migrate_plus.migration.stanford_localist_importer.yml
- Smart date adjustment for end values.
- Automation might fail until the `stanford_migrate` is merged.
- 1/20/22
- Medium
1. follow steps in https://github.com/SU-SWS/stanford_migrate/pull/46
=> Adjust localist end dates for Smart Date "All Day"

tests/codeception/acceptance/Content/SearchBlockCest.php
- Add more test steps to re-enable the search block.
- 1/25
- medium
nothing to test.
=> Add more steps to the site search disable tests

config/sync/block.block.stanford_basic_search.yml, tests/codeception/acceptance/Content/SearchBlockCest.php
=> Fixed the visibility conditions for the search block

config/sync/views.view.stanford_event_series.yml, config/sync/views.view.stanford_events.yml, config/sync/views.view.stanford_events_past.yml, config/sync/views.view.stanford_news.yml, config/sync/views.view.stanford_person.yml, config/sync/views.view.stanford_person_list_terms_first.yml, config/sync/views.view.stanford_publications.yml
- Configuration changes to make the "load more" buttons for infinite scrollers be more descriptive for a11y purposes.
- Code cutoff for 2.4.0
- 2
- Normal
3. Create a bunch of events.
4. Verify the "Load More" button at the bottom of an infinite scroll list has the text "Load More Events".
5. If you want, create a bunch of people, news, or publications and make sure the text is updated correctly for those as well.
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new …
=> D8CORE-5236: Updated text on "Load More" buttons to be more descriptive

composer.json, tests/codeception/acceptance/Users/IntranetCest.php
=> BOT-8: Adjusted file upload access test for Intranet and allow_file_uploads.

config/sync/filter.format.stanford_html.yml
- Added `id` attribute for wysiwyg
- 3/5
- medium
1. checkout branch
2. import config
3. add some markup to a wyiswyg and add an `id` attribute to a `<p>` or `<div>` tag
4. save and verify the page renders the id attribute.
=> D8CORE-4713 Added id attribute for several wysiwyg tags

config/sync/layout_library.layout.stanford_basic_page_full.yml
=> D8CORE-4526 Adjust full width layout for page title position

config/sync/pathauto.pattern.event_nodes.yml, config/sync/pathauto.pattern.event_types.yml, config/sync/pathauto.pattern.news_topics.yml, config/sync/pathauto.pattern.person.yml, config/sync/pathauto.pattern.stanford_publication_topics.yml, config/sync/pathauto.pattern.stanford_publications.yml, tests/codeception/acceptance/Content/PersonCest.php
- Updated pathauto patterns to be better for SEO and users.
- 3/15
- medium
2. checkout the branch in https://github.com/SU-SWS/stanford_profile_helper/pull/183
3. `blt drupal:update` or `drush updb -y; drush cim -y`
4. create a event type taxonomy term
5. create an event using that term as the event type
6. verify the event type is part of the `event/[term]` url
=> D8CORE-3345 Updated path auto pattern for events, news, and people

.circleci/config.yml
- D8CORE-3975 Created shared tags vocabulary and fields
- D8CORE-5615 Shared tags view with card display
- D8CORE-5611 D8CORE-5610 Adjust taxonomy vocabs and fields
- Refactor taxonomy terms and views for those pages
- Adjusted tests
- adjust tests
- adjusted test
- fix container widths
- Adjusted layout builder classes
- Flatten shared tags vocab
- Update auto labeler (#516)
- Updated tests for shs patch
- Added tests for list paragraphs
- use circleci context
1. …
=> circle context

composer.json, config/sync/core.extension.yml, config/sync/filter.format.stanford_html.yml, config/sync/filter.format.stanford_minimal_html.yml, config/sync/responsive_tables_filter.settings.yml
- Add and configured responsive tables_filter module
- 4/20
- medium
1. composer require su-sws/stanford_profile:dev-D8CORE-5666`
2. import configs `blt drupal:update`
3. create a basic page with a table in the WYSIWYG (ensure it has some headers)
4. view it on mobile.
=> D8CORE-5666 Enabled and configured responsive_tables_filter module

config/sync/views.view.stanford_courses.yml
- Changed the instructors to come as a list
- soonish
- Normal
- Normal
2. Check out the https://github.com/SU-SWS/stanford_courses/pull/90
3. Rebuild Cache and import config `drush cr; drush ci`
4. Navigate to `courses` page. 
5. See that the instructors are in a list.
- Is there a config:export in this PR that changes the config sync directory? This is the config.
- [D8CORE-5768
](https://stanfordits.atlassian.net/browse/D8CORE-5768)
- https://github.com/SU-SWS/stanford_courses/pull/90
- https://github.com/SU-SWS/stanford_profile/pull/527
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCj …
=> D8CORE-5768: changing to a list for the instructors

config/sync/views.view.taxonomy_term_pages.yml
- Changed the tag on the `<header>` to a div with a class
- Soonish
- Normal
- Normal
3. Navigate to filtered people pages
4. Verify there is no font size difference on the filtered by:
- [D8CORE-5729](https://stanfordits.atlassian.net/browse/D8CORE-5729)
- https://github.com/SU-SWS/stanford_profile/pull/528 
- https://github.com/SU-SWS/stanford_person/pull/165
- [HTML …
=> D8CORE-5729  styling updates

config/sync/core.entity_view_display.media.embeddable.default.yml
- Embeddables were stripping out `<object>` tags.  This adds that tag to the list of allowed tags in embeddables.
2. `drush cr ; drush ci`
3. Go to a test page, and create a new embeddable.
4. Use this code for the embed.
```
<script type='text/javascript' src='https://tableau.stanford.edu/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 1016px; height: 1014px;'><object class='tableauViz' width='1016' height='1014' style='display:none;'><param name='host_url' …
```
=> D8CORE-5627: added <object> and <param> to allowed tags in embeddables

config/sync/views.view.stanford_news.yml, config/sync/views.view.stanford_publications.yml
- Added the grid-container-3 to the three across.
- 4/26
- Normal
- Normal
2. Rebuild Cache and import config `drush ci`
3. add content to News and publications
4. Navigate to a news and publication node
5. Verify the cards are 3 across and not stacked or 4 across.
- Is there a config:export in this PR that changes the config sync directory? yes
- News and Publications
-  [D8CORE-5578](https://stanfordits.atlassian.net/browse/D8CORE-5778)
- [HTML Validator](https://validator.w3.org/)
- …
=> D8CORE-5778: adding the grid col 3 for three across

config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml, config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
- Adding an su-list-unstyled class to the taxonmy terms. 
- 4/27
- Normal
- Normal
2. Rebuild Cache and import config `drush ci`
3. If you have the `amptesting-dev` content, then on the homepage at the top cards.
5. Verify the terms are in a row.
- Is there a config:export in this PR that changes the config sync directory? Yes
- Publications and News Taxonomy terms
- [D8CORE-5748](https://stanfordits.atlassian.net/browse/D8CORE-5748)
- https://github.com/SU-SWS/stanford_profile_helper/pull/196
- https://github.com/SU-SWS/stanford_profile/pull/533
- [HTML …
=> D8CORE-5748: Adding a listy style to the taxonomy terms

config/sync/views.view.stanford_courses.yml
- The Courses view needed a tweak to make sure it was respecting the item limit chosen by the content creator when setting up a list paragraph in card view.
- asap
- regular
- high
3. Import some courses.
4. Create a list paragraph to display the courses in card grid mode.  Add a limit on how many items to show.  Save, and view the page to verify that the limit is respected.
- Other PRs
- Anyone who …
=> D8CORE-5833: Fix for courses view to respect item limit in card grid

config/sync/oembed_providers.provider.sul_embed_service.yml, tests/codeception/acceptance/Media/MediaCest.php
- The SUL oEmbeds started using a new oEmbed provider name, which isn't available in the `https://oembed.com/providers.json` official list.  This adds the provider to our stack. 
- 5/19/22
- low
- normal
2. `drush cim`
3. Try to create an oEmbed media item using a resource from the Stanford Digital Repository.  I used `https://purl.stanford.edu/fr477qg2469` for testing.
4. Verify that you can create the oEmbed successfully and it loads correctly on the page.
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it …
=> D8CORE-5824: Added a second provider for Stanford University Library oEmbeds

composer.json, config/sync/views.view.content.yml
- A one-line config change to allow content authors/editors to sort the "All Content" view by author.
- 5/18/22
- Low
- Normal
2. `drush cim`
3. Navigate to `/admin/content`
4. Add a couple of basic pages or whatever.
5. Verify that you can sort the `/admin/content` list by Author.
- Other PRs
- [Accessibility Manual Test …
=> D8CORE-2215: Let editors sort content by author

config/sync/editor.editor.stanford_html.yml, config/sync/filter.format.stanford_html.yml
- This adds the configs necessary to support the `<abbr>` button in CKEditor.
- This goes with: https://github.com/SU-SWS/stanford_text_editor/pull/54
- 5/18/22
- low
- normal
1. Check out this branch and the branch in: https://github.com/SU-SWS/stanford_text_editor/pull/54
2. 'drush cim && drush cr`
3. Clear your browser cache, since there's new javascript
4. Create a basic page with a text area.  
5. In the text area, confirm that you can see the Abbreviation button: 
6. Verify the button works as expected.  You can put in an abbreviation, and the meaning, and it'll add the element correctly to the page.
- Other PRs
- Any …
=> D8CORE-1835: Added abbr buttons to ckeditor

tests/codeception/functional/Paragraphs/GalleryCest.php
=> Updated some codeception tests

composer.json
- The `ext-intl` php extension can't be enabled on Acquia. The `seboettg/citeproc-php` package requires `ext-intl` in their latest version. We had it locked to a commit hash on the `master` branch via `dev-master`, but composer doesn't respect the hash and pulls from the branch's latest `composer.json` to build requirements.
4. Verify...
- Does this PR …
=> Locked citeprocphp to version 2.4.1, pre ext-intl requirement.

config/sync/core.entity_form_display.node.stanford_publication.default.yml, config/sync/core.entity_view_display.node.stanford_person.default.yml, config/sync/core.entity_view_display.node.stanford_publication.default.yml, config/sync/core.entity_view_display.node.stanford_publication.search_indexing.yml, config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml, config/sync/core.entity_view_display.node.stanford_publication.teaser.yml, config/sync/field.field.node.stanford_publication.su_publication_author_ref.yml, config/sync/field.storage.node.su_publication_author_ref.yml, config/sync/views.view.stanford_publications.yml, tests/codeception/acceptance/Content/PublicationsCest.php
=> D8CORE-4867 Publication lists on people pages

modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css, modules/stanford_profile_styles/dist/css/base/admin/field_widgets.css, modules/stanford_profile_styles/dist/css/base/admin/node_forms.css, modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css, modules/stanford_profile_styles/dist/css/base/views/search.css, modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css, modules/stanford_profile_styles/dist/css/component/node/stanford_page.css, modules/stanford_profile_styles/dist/css/component/node/stanford_page.layout.full-width.css, modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css, modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css, modules/stanford_profile_styles/dist/css/component/paragraph/spacer.css, modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css, modules/stanford_profile_styles/dist/css/layout/layout.css, modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
- making sure content that gets wrapped in a `table-saw-content` automatically will have the right font size. 
- Jun 5
- Normal
- Normal
2. Rebuild Cache and import config `drush cr ; `
3. Navigate to a page. 
4. Add a text paragraph with text in a table. Some text plain, some in a bulleted or  numbered list
6. Verify the font sizes are all the same.
- Is there a config:export in this PR that changes the config sync directory? NO
- [D8CORE-4489
](https://stanfordits.atlassian.net/browse/D8CORE-4489)
- [HTML …
=> D8CORE-4489: fixing font sizes within tables

composer.json, config/sync/core.entity_form_display.node.stanford_event.default.yml, config/sync/core.extension.yml, config/sync/field.field.node.stanford_event.su_event_sponsor.yml, config/sync/field.storage.node.su_event_sponsor.yml, modules/stanford_events/stanford_events.install
- This is a re-roll of the PR at: https://github.com/SU-SWS/stanford_profile/pull/556
- D8CORE-2274: changed button text to "Add another sponsor"
- D8CORE-4663: removed 120 character limit on the sponsor field. 
- 🤷 
- low
- normal
2. `blt drupal:update` <-- database updates have to run as well as new configs.
3. Create an Event item.
4. Verify the text change on the button, and that there is no longer a 120 character limit for the sponsor field: 
- Other PRs …
=> D8CORE-2274: Updated event sponsor field

config/sync/config_pages.type.stanford_events_importer.yml, config/sync/config_pages.type.stanford_person_importer.yml, config/sync/core.entity_form_display.config_pages.stanford_person_importer.default.yml, config/sync/core.entity_view_display.config_pages.stanford_person_importer.default.yml, config/sync/field.field.config_pages.stanford_person_importer.su_person_orphan.yml, config/sync/field.storage.config_pages.su_person_orphan.yml, config/sync/migrate_plus.migration.stanford_events_importer.yml, config/sync/migrate_plus.migration.stanford_localist_importer.yml, config/sync/migrate_plus.migration.stanford_publications.yml, config/sync/migrate_plus.migration.su_stanford_person.yml, modules/stanford_person/modules/stanford_person_importer/src/Cap.php, modules/stanford_person/modules/stanford_person_importer/src/CapInterface.php, modules/stanford_person/modules/stanford_person_importer/src/Config/ConfigOverrides.php, modules/stanford_person/modules/stanford_person_importer/tests/src/Unit/CapTest.php, modules/stanford_person/modules/stanford_person_importer/tests/src/Unit/Config/ConfigOverridesTest.php
=> Fix error when the access token expires

.circleci/config.yml, composer.json, config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml, config/sync/core.entity_view_display.media.embeddable.media_library.yml, config/sync/core.entity_view_display.media.file.media_library.yml, config/sync/core.entity_view_display.media.google_form.media_library.yml, config/sync/core.entity_view_display.media.image.media_library.yml, config/sync/core.entity_view_display.media.image.stanford_image_large.yml, config/sync/core.entity_view_display.media.image.stanford_image_large_square.yml, config/sync/core.entity_view_display.media.image.stanford_image_medium.yml, config/sync/core.entity_view_display.media.image.stanford_image_medium_square.yml, config/sync/core.entity_view_display.media.image.stanford_image_stanford_circle.yml, config/sync/core.entity_view_display.media.image.stanford_image_thumb_square.yml, config/sync/core.entity_view_display.media.image.thumbnail.yml, config/sync/core.entity_view_display.media.stanford_gallery_images.media_library.yml, config/sync/core.entity_view_display.media.video.media_library.yml, config/sync/core.extension.yml, config/sync/jsonapi.settings.yml, config/sync/views.view.media.yml, config/sync/views.view.media_library.yml
=> Drupal 9.4 support

tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php, tests/codeception/functional/Paragraphs/BannerCest.php, tests/codeception/functional/Paragraphs/EntityReferenceCest.php, tests/codeception/functional/Paragraphs/GalleryCest.php, tests/codeception/functional/Paragraphs/WYSIWYGCest.php
=> Adjusted functional tests

composer.json, config/sync/field.field.media.embeddable.field_media_embeddable_code.yml, config/sync/media.type.embeddable.yml, modules/stanford_intranet/src/Config/ConfigOverrider.php, tests/codeception/acceptance/Media/MediaCest.php
- Configured new embed code validations from https://github.com/SU-SWS/stanford_media/pull/127
- 6/30
- medium
- see steps in https://github.com/SU-SWS/stanford_media/pull/127
=> D8CORE-5128 Enable embed code validators

config/sync/core.entity_view_display.media.embeddable.default.yml, tests/codeception/acceptance/Media/MediaCest.php
- We add additional allowed tags to the freeform embeddables field so that it roughly matches the tags available in WYSIWYG paragraphs.
- 7/7
- 1
- normal
3. Go to create a new embed.  You must be logged in as an administrator to have full access to the freeform embeddable field
4. Make your freeform embed code include one or more of the allowed tags: `a aside audio b blockquote br button caption cite code dd dl div drupal-media dt em embed form h1 h2 h3 h4 h5 hr i iframe img input label li object ol option p param pre s script select source span strong sub sup table tbody textarea td tfoot th thead tr ul video`
5. Verify you can save the embeddable with no problems, and that none of the tags you included …
=> D8CORE-6000: Added additional html elements to embeddables allow list

content/menu_link_content/178b9e51-c3bb-4cd5-a3ac-fe241e27f083.yml, content/menu_link_content/26a314fe-33aa-4660-b06a-97b26dc75baf.yml, content/menu_link_content/3e24cd94-5f2b-4fb2-806c-bcb830cdc2dc.yml, content/menu_link_content/752de90b-4130-402f-8601-57f8d916799c.yml, content/menu_link_content/a5f9f185-b376-4cab-b3bd-dc3b03617cea.yml, content/menu_link_content/bdf424e8-7106-414d-b333-7f5add6e8c8a.yml, content/menu_link_content/c2c22d8b-eb7c-4804-9332-4ec2aff3391a.yml, content/menu_link_content/d91b714a-4609-41c5-a9c4-d8140ed3a764.yml, content/menu_link_content/e635159f-4b50-4016-bbf6-41113adbff65.yml, modules/stanford_profile_helper/src/EventSubscriber/EntityEventSubscriber.php, modules/stanford_profile_helper/src/EventSubscriber/PreprocessEventSubscriber.php, modules/stanford_profile_helper/src/Plugin/Validation/Constraint/MenuLinkItemConstraint.php, modules/stanford_profile_helper/src/Plugin/Validation/Constraint/MenuLinkItemConstraintValidator.php, modules/stanford_profile_helper/stanford_profile_helper.module, modules/stanford_profile_helper/stanford_profile_helper.services.yml, modules/stanford_profile_helper/tests/src/Kernel/EventSubscriber/EntityEventSubscriberTest.php, modules/stanford_profile_helper/tests/src/Unit/Plugin/Validation/Constraint/MenuLinkItemConstraintValidatorTest.php, modules/stanford_profile_styles/js/colorbox.js, modules/stanford_profile_styles/stanford_profile_styles.libraries.yml, modules/stanford_text_editor/tests/src/Kernel/StanfordTextEditorTest.php, tests/codeception/acceptance/Content/DefaultContentCest.php, themes/stanford_basic/src/js/stanford_basic.behavior.js, themes/stanford_basic/stanford_basic.libraries.yml
=> Validate menu items for absoluate urls

tests/codeception/functional/Paragraphs/WYSIWYGCest.php
=> Add functional tests for wysiwyg button focus

modules/stanford_person/modules/stanford_person_importer/src/Config/ConfigOverrides.php, modules/stanford_person/modules/stanford_person_importer/tests/src/Unit/Config/ConfigOverridesTest.php
- Improve person importer url fetching with some error handleing
- refactor
4. Verify...
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, …
=> improve cap config

config/sync/core.entity_form_display.paragraph.stanford_banner.default.yml, config/sync/core.entity_form_display.paragraph.stanford_card.default.yml, config/sync/core.entity_form_display.paragraph.stanford_entity.default.yml, config/sync/core.entity_form_display.paragraph.stanford_gallery.default.yml, config/sync/core.entity_form_display.paragraph.stanford_lists.default.yml, config/sync/core.entity_form_display.paragraph.stanford_media_caption.default.yml, config/sync/core.extension.yml, config/sync/editor.editor.stanford_html.yml, config/sync/editor.editor.stanford_minimal_html.yml, tests/codeception/functional/Content/BasicPageParagraphsCest.php, tests/codeception/functional/Paragraphs/BannerCest.php, tests/codeception/functional/Paragraphs/EntityReferenceCest.php
=> D8CORE-6006 Disable link attributes module

config/sync/field_validation.rule_set.config_pages_stanford_basic_site_settings.yml, config/sync/google_analytics.settings.yml
=> Updated field validation for google analytics and allow multiple property ids

config/sync/auto_entitylabel.settings.node.stanford_person.yml, config/sync/core.base_field_override.node.stanford_person.title.yml, config/sync/core.entity_form_display.node.stanford_person.default.yml, config/sync/field.field.node.stanford_person.su_person_short_title.yml, config/sync/pathauto.pattern.person.yml, config/sync/views.view.stanford_person.yml, config/sync/views.view.taxonomy_term_pages.yml, modules/stanford_profile_helper/js/stanford_profile_helper.ajax_views.js, modules/stanford_profile_helper/stanford_profile_helper.libraries.yml, modules/stanford_profile_helper/stanford_profile_helper.module
=> D8CORE-5656 D8CORE-6215 D8CORE-6048 Adjustments to people node form and views

config/sync/core.entity_form_display.citation.su_article_journal.default.yml, config/sync/core.entity_view_display.citation.su_article_journal.default.yml, config/sync/field.field.citation.su_article_journal.su_journal_publisher.yml, config/sync/field.field.citation.su_article_journal.su_publisher.yml, config/sync/field.storage.citation.su_journal_publisher.yml, tests/codeception/acceptance/Content/PublicationsCest.php
- Journals need a Journal Publisher field.  Up until now, users have been using the "Publisher" field as the journal name, so we update the label on that field to make it clear how it's used, and we add a Journal Publisher field to hold the publisher of the journal (e.g., Elsevier, IEEE, etc.)
- 3.1.0 code cutoff.
- low
- normal
3. Create a publication with a Journal citation.
4. Verify that you can store (and view) the journal title and the journal publisher on the Publication page.  The Citation styles don't change in list views.
- Other PRs …
=> D8CORE-5955: Added journal publisher field, updated publisher label.

composer.json
Mike's patch has been integrated into a new release (2.0.3) today: https://www.drupal.org/project/token_or and so is no longer applicable.
4. Verify...
- Other PRs
- Any other contextual information that might be helpful (e.g., description of …
=> Removed token_or patch

composer.json
- may need to tag the `stanford_fields` module for a release before this will work.
4. Verify...
- Other PRs
- Anyone who should …
=> Revert composer.json

config/sync/core.entity_form_display.paragraph.stanford_accordion.default.yml, config/sync/core.entity_form_display.paragraph.stanford_banner.default.yml, config/sync/core.entity_form_display.paragraph.stanford_card.default.yml, config/sync/core.entity_form_display.paragraph.stanford_entity.default.yml, config/sync/core.entity_form_display.paragraph.stanford_gallery.default.yml, config/sync/core.entity_form_display.paragraph.stanford_lists.default.yml, config/sync/core.entity_form_display.paragraph.stanford_media_caption.default.yml, config/sync/core.entity_form_display.paragraph.stanford_person_cta.default.yml, config/sync/core.entity_form_display.paragraph.stanford_schedule.default.yml, config/sync/core.entity_form_display.paragraph.stanford_spacer.default.yml, config/sync/core.entity_form_display.paragraph.stanford_wysiwyg.default.yml, config/sync/core.entity_view_display.node.stanford_policy.default.yml, config/sync/core.entity_view_display.node.stanford_policy.teaser.yml, config/sync/views.view.policies.yml
- Added view to list the child pages for each book/policy page.
- soon
- high
2. import configs
3. view the policy page that has children pages.
=> Added view to display policy child pages

config/sync/views.view.search.yml, tests/codeception/acceptance/Content/BasicPageCest.php
- Added a "Last Updated" to the search results items.
- 10/15
- low
2. import configs
3. create some page
4. use the site search to search for some words you added to the page
5. verify the last updated date is shown.
=> D8CORE-5250 Add "Last Updated" to search results items

config/sync/migrate_plus.migration.stanford_localist_importer.yml, config/sync/search_api.index.full_site_content.yml, config/sync/views.view.search.yml, modules/stanford_policy/src/EventSubscriber/StanfordPolicySubscriber.php, modules/stanford_policy/tests/src/Kernel/EventSubscriber/StanfordPolicySubscriberTest.php, tests/codeception/acceptance/Content/PersonCest.php, tests/codeception/acceptance/Content/PolicyCest.php
=> D8CORE-6312 Fix node title not reflecting the changes

composer.json, config/sync/core.extension.yml, config/sync/ultimate_cron.job.fast_404_generator_cron.yml
- Added and configured Fast 404 module and generator
- 10/13
- high
1. follow steps in https://github.com/SU-SWS/acsf-cardinalsites/pull/273
=> Added Fast 404 module

config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml, config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml, config/sync/field.field.config_pages.stanford_basic_site_settings.su_hide_ext_link_icons.yml, config/sync/field.storage.config_pages.su_hide_ext_link_icons.yml, content/config_pages/0d7e973e-6b97-4243-a373-d486a581eb84.yml, modules/stanford_profile_styles/stanford_profile_styles.module, src/Plugin/InstallTask/SiteSettings.php, tests/codeception/functional/Contrib/ExtLinkCest.php
- Note: I made a new PR since I had the new policy stuff and couldn't really go backwards.  
- Added a toggle in the theme to turn off the external links
- 10/9
- Normal
- effects the Stanford Basic theme
- effect all Subthemes if turned off
- Normal
3. Navigate to your local Site Setting page: http://[localhost]/admin/config/system/basic-site-settings
4. Check the box to hide external link icons.
5. create some links that are local and external.
6. Verify only the ext icon goes away and no other visible change.
- …
=> D8CORE-6251: Added a toggle in the theme to turn off the external links

themes/stanford_basic/templates/navigation/book-navigation.html.twig
- making sure the next and previous buttons have unique ids and aria-labelledby.
- note: is this a good approach? Is it likely the two blocks with randoms would end up with the same number?
- Soon
- Normal
- Normal
3. Navigate to a policy page.
4. Verify two navs for the next and previous have unique ids and aria-labelled-by's
[- D8CORE-6329](https://stanfordits.atlassian.net/browse/D8CORE-6329)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEP …
=> D8CORE-6329: unique ids for prev/next buttons

composer.json, config/sync/migrate_plus.migration.stanford_courses.yml
- Re-roll of https://github.com/SU-SWS/stanford_profile/pull/627/ to account for the new stanford_profile_helper module structure.
- Goes with: https://github.com/SU-SWS/stanford_profile_helper/pull/213
- Today
- medium. affects 17 sites.
- high
1. `composer require su-sws/stanford_profile:dev-D8CORE-6237-2`
2. `blt drupal:update`
3. Test as per: https://github.com/SU-SWS/stanford_profile/pull/627/
- Is there a config:export in this PR that changes the config sync directory? yes
- Other PRs
- [AMP …
=> D8CORE-6237: Corrected courses migration

CHANGELOG.md, composer.json, config/sync/config_split.config_split.dev.yml, config/sync/config_split.config_split.prod.yml, config/sync/config_split.config_split.stage.yml
=> excise memcache

config/sync/field.field.log.policy.su_policy_date.yml
=> DEVOPS-000: SMRT quotes R dumb

composer.json, stanford_profile.profile
=> Updated hook event dispatcher

config/sync/field.field.node.stanford_policy.su_policy_effective.yml
- Fix effective date label typo when you create a policy
- When convenient
- Normal
2. Create a new policy and confirm the effective date label is correct
=> D8CORE-000 | @jdwjdwjdw | Fix policy typo

config/sync/views.view.stanford_events.yml
Reverts SU-SWS/stanford_profile#669
=> Revert "D8CORE-4495: changing past events text" (bad grammar)

composer.json, config/sync/metatag.metatag_defaults.front.yml, config/sync/metatag.metatag_defaults.node.yml, config/sync/metatag.metatag_defaults.node__stanford_news.yml, config/sync/metatag.metatag_defaults.node__stanford_person.yml
=> Update metatag module and config

config/sync/block.block.minimally_branded_subtheme_main_anchor.yml, config/sync/block.block.stanford_basic_main_anchor.yml, stanford_profile.post_update.php, tests/codeception/acceptance/Content/BasicPageCest.php
=> D8CORE-6633 Add skip link anchor to the search page

tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
=> Adjust test to run a little faster

.github/workflows/tests.yml, composer.json, config/sync/chosen.settings.yml, config/sync/node.type.stanford_policy.yml, config/sync/xmlsitemap.settings.node.stanford_policy.yml, config/sync/xmlsitemap.settings.yml, tests/codeception/acceptance/SystemCest.php
=> Add system test
